<div class="wrapper">
    <h2>Cấu hình hệ thống - Cập nhật setting management</h2>
</div>
<div class="wrapper">
    <form id="validate" class="form" method="post" action="<?php echo $this->adminUrl('config-setting/submit-edit'); ?>">
        <fieldset>
            <div class="widget">
                <div class="formRow">
                    <label>Ghi chú:<span class="req">*</span></label>
                    <div class="formRight">
                        <?php echo $this->formText(
                            'note',
                            $this->dataInfo ? $this->dataInfo->{DbTable_Config_Setting::COL_CONFIG_SETTING_NOTE} : null,
                            array('class' => 'validate[required]')
                        ); ?>
                    </div>
                    <div class="clear"></div>
                </div>
                <div class="formRow">
                    <label>Giá trị:<span class="req">*</span></label>
                    <div class="formRight">
                        <?php echo $this->formText(
                            'value',
                            $this->dataInfo ? $this->dataInfo->{DbTable_Config_Setting::COL_CONFIG_SETTING_VALUE} : null,
                            array('class' => 'validate[required]')
                        ); ?>
                    </div>
                    <div class="clear"></div>
                </div>
                <div class="formRow">
                    <label>Kiểu:<span class="req">*</span></label>
                    <div class="formRight">
                        <?php echo $this->formTextarea(
                            'type',
                            $this->dataInfo ? $this->dataInfo->{DbTable_Config_Setting::COL_CONFIG_SETTING_TYPE} : null,
                            array('rows' => 3, 'class' => 'validate[required]')
                        ); ?>
                    </div>
                    <div class="clear"></div>
                </div>
                <div class="formRow">
                    <label>Admin:<span class="req">*</span></label>
                    <div class="formRight">
                        <?php echo $this->formSelect(
                            'fk_admin',
                            $this->dataInfo ? $this->dataInfo->{DbTable_Config_Setting::COL_FK_ADMIN} : null,
                            array('class' => 'validate[required]'),
                            array('' => ' -- Chọn') + $this->adminData
                        ); ?>
                    </div>
                    <div class="clear"></div>
                </div>
                <div class="formSubmit">
                    <?php echo $this->formHidden(
                        'id',
                        $this->dataInfo ? $this->dataInfo->{DbTable_Config_Setting::COL_CONFIG_SETTING_ID} : null
                    ); ?>
                    <input type="submit" value="Cập nhật" class="redB" />
                </div>
            </div>
        </fieldset>
    </form>
</div>