<section class="row twelvecol man">
    <div style="border: 0px none;" class="ui-tabs ui-widget ui-widget-content ui-corner-all" id="tabs"></div>
    <!--
    <div id="logo" align="center">
        <div style="font-size:72px;">Shipmore</div>
        <div style="font-style:italic; margin-top:50px;">
            By <strong>Tin.Trang</strong> &lt;trangthanhtin@gmail.com&gt; & <strong>Phong.Pham</strong> &lt;xitrumhaman@gmail.com&gt;
        </div>

        <div style="font-style:italic; margin-top:80px;">
            Your last login at <? echo $this->adminInfo->lastlogin; ?> on <? echo $this->adminInfo->lastlogin_ip; ?>
        </div>
    </div>
    -->
</section>