<div id="navbar" class="navbar-collapse collapse">
    <ul class="nav navbar-nav">
        <li class=""><a href="/" style="margin: 0px;"><img src="<?php echo HOST_STATIC_DEFAULT;?>images/logo_small.png" style="height: 50px;"></a></li>

        <!--<li class="active"><a href="/tim-kiem-ban-do?district=776">HIỂN THỊ THEO BẢN ĐỒ</a></li>-->
        <li class=""><a href="/tim-kiem?<?php echo $this->queryPagination;?>">HIỂN THỊ THEO DANH SÁCH</a></li>
        <li style=""><a href="/dang-tin-cho-thue.html">ĐĂNG TIN CHO THUÊ</a></li>
        <li style=""><a href="/dang-tin-tim-phong.html">ĐĂNG TIN TÌM PHÒNG</a></li>

        <!--<li class="pull-right"><a href="category.html" class="btn">ĐĂNG TIN</a></li>-->
    </ul>
</div><!--/.nav-collapse -->