<div style="background-color: #E2E2E2;display:none;" id="search_pane">

    <div class="container">
        <div class="row">
            <div class="col-md-12 map-navigation-positioning">
                <div class="map-navigation-wrapper">
                    <div class="map-navigation">
                        <form role="search" method="GET" id="searchformTop" class="searchform" action="/tim-kiem-ban-do">
                            <div class="search_field">
                                <div class="row">
                                    <div class="col-xs-4 padding5">
                                        <div class="form-group">
                                            <div class="form-group">
                                                <input type="text" class="form-control" id="search_keyword" name="key"
                                                       value="<?php echo isset($this->key) ? $this->key : null; ?>"
                                                       placeholder="Vị trí khu vực tìm phòng">
											    <input type="hidden" id="lat"  name="lat" value="<?php echo isset($this->lat) ? $this->lat : null; ?>">	   
												<input type="hidden" id="lng" name="lng" value="<?php echo isset($this->lng) ? $this->lng : null; ?>">	   
                                            </div>
                                        </div>
                                    </div>

                                    
                                    <div class="col-xs-4 padding5">
                                        <div class="form-group">
                                            <?php echo $this->formSelect(
                                                'price-value',
                                                isset($this->priceValue) ? $this->priceValue : null,
                                                array(
                                                    'class' => 'form-control price',
                                                    'id' => 'search_room_prices'
                                                ),
                                                array(
                                                    '' => '--Chọn mức giá--',

                                                    1 => '< 1.000.000',
                                                    2 => '1000.000 - 3.000.000',
                                                    3 => '3.000.000 - 5.000.000',
                                                    4 => '5.000.000 - 10.000.000',
                                                    5 => '> 10.000.000',

                                                )
                                            ); ?>
                                        </div>
                                    </div>
                                    <div class="col-xs-3 padding5">
                                        <label class="radio-inline" style="color:white;">
                                            <input type="checkbox" name="type-search" id="type_search"
                                                   value="1" checked disabled>
                                            Xem bản đồ
                                        </label>

                                        <div class="form-group  pull-right">
                                            <button type="submit" class="btn btn-default btn_search_box  blue-steel">Tìm
                                                kiếm
                                            </button>
                                        </div>
                                    </div>
                                </div>


                            </div>
                        </form>
                    </div>
                    <!-- /.map-navigation -->
                </div>
                <!-- /.map-navigation-wrapper -->
            </div>
            <!-- /.col-sm-3 -->
        </div>
        <!-- /.row -->
    </div>
</div>