<div class="container">
    <div class="row">
        <div class="col-md-12 map-navigation-positioning">
            <div class="map-navigation-wrapper">
                <div class="map-navigation">
                    <form role="search" method="GET" id="searchformTop" class="searchform" action="/tim-kiem-ban-do">
                        <div class="search_field">
                            <div class="row">
                                <div class="col-xs-6 padding5">
                                    <div class="form-group">
                                        <div class="form-group">
                                            <input type="text" class="form-control" id="search_keyword" name="key"
                                                   value="<?php echo isset($this->key) ? $this->key : null; ?>"
                                                   placeholder="Nhập thông tin cần tìm">
                                        </div>
                                    </div>
                                </div>
                                <div class="col-xs-3 padding5">
                                    <div class="form-group">
                                        <?php echo $this->formSelect(
                                            'category',
                                            isset($this->category) ? $this->category : null,
                                            array(
                                                'class' => 'form-control',
                                                'id' => 'search_room_type'
                                            ),
                                            array(
                                                '' => '--Chọn loại tin--',
                                                2 => 'Phòng cho thuê',
                                                1 => 'Nhà cho thuê',
                                                3 => 'Tìm bạn ở ghép'

                                            )
                                        ); ?>

                                    </div>
                                </div>

                                <div class="col-xs-3 padding5">
                                    <div class="form-group">
                                        <?php echo $this->formSelect(
                                            'district',
                                            isset($this->district) ? $this->district : null,
                                            array(
                                                'class' => 'form-control',
                                                'id' => 'search_district'
                                            ),
                                            array(
                                                '' => '--Chọn Quận--',
                                                760 => 'Quận 1',
                                                769 => 'Quận 2',
                                                770 => 'Quận 3',
                                                773 => 'Quận 4',
                                                774 => 'Quận 5',
                                                775 => 'Quận 6',
                                                778 => 'Quận 7',
                                                776 => 'Quận 8',
                                                763 => 'Quận 9',
                                                771 => 'Quận 10',
                                                772 => 'Quận 11',
                                                761 => 'Quận 12',
                                                762 => 'Quận Thủ Đức',
                                                764 => 'Quận Gò Vấp',
                                                765 => 'Quận Bình Thạnh',
                                                766 => 'Quận Tân Bình',
                                                767 => 'Quận Tân Phú',
                                                768 => 'Quận Phú Nhuận',
                                                777 => 'Quận Bình Tân',
                                                783 => 'Huyện Củ Chi',
                                                784 => 'Huyện Hóc Môn',
                                                785 => 'Huyện Bình Chánh',
                                                786 => 'Huyện Nhà Bè',
                                                787 => 'Huyện Cần Giờ',
                                            )
                                        ); ?>

                                    </div>
                                </div>
                            </div>
                            <div class="row">


                                <div class="col-xs-3 padding5">
                                    <div class="form-group">
                                        <?php echo $this->formSelect(
                                            'price-value',
                                            isset($this->priceValue) ? $this->priceValue : null,
                                            array(
                                                'class' => 'form-control price',
                                                'id' => 'search_room_prices'
                                            ),
                                            array(
                                                '' => '--Chọn mức giá--',

                                                1 => '< 1.000.000',
                                                2 => '1000.000 - 3.000.000',
                                                3 => '3.000.000 - 5.000.000',
                                                4 => '5.000.000 - 10.000.000',
                                                5 => '> 10.000.000',

                                            )
                                        ); ?>
                                    </div>
                                </div>
                                <div class="col-xs-3 padding5">
                                    <div class="form-group">
                                        <?php echo $this->formSelect(
                                            'area',
                                            isset($this->area) ? $this->area : null,
                                            array(
                                                'class' => 'form-control',
                                                'id' => 'search_dientich'
                                            ),
                                            array(
                                                '' => '--Chọn diện tích--',
                                                1 => '< 20 m2',
                                                2 => '20 m2 - 30 m2',
                                                3 => '30 m2 - 50 m2',
                                                4 => '50 m2'

                                            )
                                        ); ?>

                                    </div>
                                </div>

                                <div class="col-xs-3 padding5">
                                    <div class="form-group">
                                        <?php echo $this->formSelect(
                                            'object',
                                            isset($this->object) ? $this->object : null,
                                            array(
                                                'class' => 'form-control',
                                                'id' => 'search_doituong'
                                            ),
                                            array(
                                                '' => '--Chọn đối tượng--',
                                                0 => 'Tất cả',
                                                1 => 'Nam',
                                                2 => 'Nữ'
                                            )
                                        ); ?>
                                    </div>
                                </div>
                                <div class="col-xs-3 padding5">
                                    <div class="form-group  pull-right">
                                        <button type="submit" class="btn btn-default btn_search_box  btn-default">Tìm
                                            kiếm
                                        </button>
                                        <a href="/dang-tin-cho-thue.html" class="btn blue-steel ">Đăng tin</a>


                                    </div>
                                </div>
                            </div>

                        </div>
                    </form>
                </div>
                <!-- /.map-navigation -->
            </div>
            <!-- /.map-navigation-wrapper -->
        </div>
        <!-- /.col-sm-3 -->
    </div>
    <!-- /.row -->
</div>