<!-- BEGIN PAGE HEADER-->
<div class="row">
    <div class="col-md-12">
        <!-- BEGIN PAGE TITLE & BREADCRUMB-->
        <h3 class="page-title">
            Administration - Thêm mới nhóm quản trị
        </h3>
        <ul class="page-breadcrumb breadcrumb">
            <li>
                <i class="fa fa-home"></i>
                <a href="/">Home</a>
                <i class="fa fa-angle-right"></i>
            </li>
            <li>
                <a href="#">nhóm quản trị</a>
            </li>
        </ul>
        <!-- END PAGE TITLE & BREADCRUMB-->
    </div>
</div>
<div class="row">
    <div class="col-md-12 ">
        <!-- BEGIN SAMPLE FORM PORTLET-->
        <div class="portlet box blue ">
            <div class="portlet-title">
                <div class="caption">
                    <i class="fa fa-gift"></i> Thông tin nhóm quản trị
                </div>
            </div>
            <div class="portlet-body form">
                <form class="form-horizontal" role="form" id="validate" method="post" target="ifrmEdit" action="<?php echo $this->adminUrl('admin-role/submit-edit'); ?>">
                    <div class="form-body">
                        <div class="form-group">
                            <label class="col-md-3 control-label">Nhóm quản trị: <span class="required" aria-required="true"> * </span>:</label>
                            <div class="col-md-6">
                                <?php echo $this->formText(
                                    'roleName',
                                    $this->dataInfo ? $this->dataInfo->{DbTable_Admin_Role::COL_ADMIN_ROLE_NAME} : null,
                                    array('class' => 'form-control validate[required]')
                                ); ?>
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-md-3 control-label">Chọn tất cả:</label>
                            <div class="col-md-6">
                                <input type="checkbox" class="group-checkable" data-set="#validate .checkboxes"/>
                            </div>

                        </div>




                        <?php foreach ($this->privilegeData as $module=>$resourceData) { ?>
                            <div class="form-group">
                                <label class="col-md-3 control-label"><?php echo $module; ?></label>
                                <div class="col-md-9">
                                    <div class="row">
                                    <?php foreach ($resourceData as $resource=>$privilegeData) { ?>

                                        <div class="col-md-4">
                                            <p><strong><?php echo $resource; ?></strong></p>
                                            <div class="checkbox-list">
                                                <?php foreach ($privilegeData as $privilege) { ?>
                                                    <label>
                                                        <?php echo $this->formCheckbox(
                                                            'privilegeArrId[]',
                                                            $privilege[DbTable_Admin_Privilege::COL_ADMIN_PRIVILEGE_ID],
                                                            array(
                                                                'checked' => in_array($privilege[DbTable_Admin_Privilege::COL_ADMIN_PRIVILEGE_ID], $this->aclArr) ? 1 : 0,
                                                                'class' => 'checkboxes'
                                                            )
                                                        );  ?>

                                                        <?php echo $privilege[DbTable_Admin_Privilege::COL_ADMIN_PRIVILEGE_NAME]; ?>
                                                    </label>
                                                <?php } ?>
                                            </div>
                                        </div>
                                    <?php } ?>
                                    </div>
                                </div>
                            </div>
                        <? } ?>
                        <div class="form-actions right">
                            <?php echo $this->formHidden(
                                'id',
                                $this->dataInfo ? $this->dataInfo->{DbTable_Admin_Role::COL_ADMIN_ROLE_ID} : null
                            ); ?>
                            <button type="submit" class="btn green">Cập nhật</button>
                        </div>
                </form>
            </div>
        </div>
        <!-- END SAMPLE FORM PORTLET-->
    </div>
    <iframe name="ifrmEdit" id="ifrmEdit" style="display: none"></iframe>
</div>