<!-- BEGIN PAGE HEADER-->
<div class="row">
    <div class="col-md-12">
        <!-- BEGIN PAGE TITLE & BREADCRUMB-->
        <h3 class="page-title">
            Administration - Nhóm quản trị
        </h3>
        <ul class="page-breadcrumb breadcrumb">
            <li>
                <i class="fa fa-home"></i>
                <a href="/">Home</a>
                <i class="fa fa-angle-right"></i>
            </li>
            <li>
                <a href="#">Quản lý Resource</a>
            </li>
        </ul>
        <!-- END PAGE TITLE & BREADCRUMB-->
    </div>
</div>
<!-- END PAGE HEADER-->

<div class="row">
    <div class="col-md-12">
        <!-- BEGIN EXAMPLE TABLE PORTLET-->
        <div class="portlet box grey-cascade">
            <div class="portlet-title">
                <div class="caption">
                    <i class="fa fa-globe"></i><?php echo $this->pagination->getTotalItemCount(); ?> dòng(s)
                </div>

            </div>
            <div class="portlet-body">
                <div class="table-toolbar">
                    <div class="btn-group">
                        <button id="btn_add_new" class="btn green">
                            Thêm mới <i class="fa fa-plus"></i>
                        </button>
                    </div>

                </div>
                <table class="table table-striped table-bordered table-hover" id="table_role">
                    <thead>
                    <tr>
                        <td>Nhóm quản trị</td>
                        <td width="30%">Ngày tạo</td>
                        <td width="10%"></td>
                    </tr>
                    </thead>
                    <tbody>
                    <?php foreach ($this->pagination as $data) {?>
                        <tr>
                            <td><?php echo $data->{DbTable_Admin_Role::COL_ADMIN_ROLE_NAME}; ?></td>
                            <td><?php echo $data->{DbTable_Admin_Role::COL_ADMIN_ROLE_CREATED_AT}; ?></td>
                            <td>
                                <a href="<?php echo $this->adminUrl('admin-role/edit/'); ?>?i=<?php echo $data->{DbTable_Admin_Role::COL_ADMIN_ROLE_ID}; ?>" title="Update" class="tipS">
                                    Cập nhật</a>
                            </td>
                        </tr>
                    <?php } ?>
                    </tbody>
                    <tfoot>
                    <tr>
                        <td colspan="99">
                            <?php echo $this->pagination; ?>
                        </td>
                    </tr>

                    </tfoot>
                </table>

            </div>
        </div>
        <!-- END EXAMPLE TABLE PORTLET-->
    </div>
</div>