<section class="mt-lg  section-product page-content">
    <div class="container">

        <div class="row">
            <div class="col-md-12">

                <div class="row">
                    <div class="col-md-3">
                        <?php echo $this->render('widgets/sidebar-left.phtml'); ?>
                    </div>

                    <div class="col-md-9">
                        <h3 class="title-h3">ĐĂNG TIN TÌM PHÒNG</h3>

                        <div class="alert alert-success mt-sm">
                            <strong><i class="fa fa-thumbs-o-up"></i> Thành công!</strong> Bạn đã gửi thông tin thành công.
                            Chúng tôi sẽ gửi lại bạn thông tin nhà trọ phù hợp trong thời gian sớm nhất.
                        </div>
                    </div>

                </div>

            </div>

        </div>
    </div>
</section>


