<div class="container">

    <div class="row">
        <div class="col-md-12">

            <div class="featured-boxes">
                <div class="row">
                    <div class="col-sm-3">

                    </div>
                    <div class="col-sm-6">
                        <div class="featured-box featured-box-primary align-left mt-xlg">
                            <div class="box-content">
                                <h4 class="heading-primary text-uppercase mb-md">Đăng ký tài khoản</h4>
                                <form action="/customer/submit-register" id="frmRegister" method="post">
                                    <div class="row">
                                        <div class="form-group">
                                            <div class="col-md-12">
                                                <label>E-mail:</label>
                                                <input type="text" value="" class="form-control input-lg" name="email" maxlength="256" minlength="6" email required>
                                            </div>
                                        </div>
                                    </div>

                                    <div class="row">
                                        <div class="form-group">
                                            <div class="col-md-6">
                                                <label>Mật khẩu</label>
                                                <input type="password" value="" class="form-control input-lg" id="password" name="password" maxlength="256" minlength="6" required>
                                            </div>
                                            <div class="col-md-6">
                                                <label>Xin nhập lại mật khẩu</label>
                                                <input type="password" value="" class="form-control input-lg" id="confirm_pass" name="confirm_pass" maxlength="256" minlength="6" email required>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="form-group">
                                            <div class="col-md-12">
                                                <label>Số điện thoại<span>*</span></label>
                                                <input type="text" value="" class="form-control input-lg phoneNumber" name="phone" maxlength="64">
                                            </div>
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="form-group">
                                            <div class="col-md-6">
                                                <label>Họ</label>
                                                <input type="text" value="" class="form-control input-lg" name="last-name">
                                            </div>
                                            <div class="col-md-6">
                                                <label>Tên</label>
                                                <input type="text" value="" class="form-control input-lg" name="first-name">
                                            </div>
                                        </div>
                                    </div>
                                    <div class="row mt-sm">
                                        <div class="col-md-6">
                                            <img src="/captcha.jpg" id="captcha-image">
                                        </div>
                                        <div class="col-md-6">
                                            <input type="text" value="" class="form-control input-lg" name="captcha" id="captcha"  title="Nhập mã xác nhận" placeholder="Mã xác nhận">
                                        </div>
                                        <div class="col-md-12">
                                            <p class="d_block">Mã xác nhận không rõ vui lòng nhấn vào <a href="javascript:void(0)" id="refreshCaptcha" class="f_bold">đây</a></p>
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="col-md-12">
                                            <?php echo $this->formHidden('backUrl', $this->backUrl ? $this->backUrl : $this->backUrl);?>
                                            <input type="submit" value="Đăng ký" class="btn btn-primary pull-right mb-xl" data-loading-text="Loading...">
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                    <div class="col-sm-3">
                    </div>
                </div>

            </div>
        </div>
    </div>

</div>