<section class="page-header">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <ul class="breadcrumb">
                    <li><a href="/">Trang chủ</a></li>
                    <li class="active">Tài khoản của tôi</li>
                </ul>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <h1>Thông tin tài khoản</h1>
            </div>
        </div>
    </div>
</section>
<div class="container">


    <div class="row profile">
        <div class="col-md-12">
            <div clbreadcrumbass="featured-boxes">
                <div class="row">
                    <div class="col-sm-3">
                        <?php echo $this->render('customer/widgets/sidebar.phtml'); ?>
                    </div>
                    <div class="col-sm-6">

                        <div class="portlet box blue">
                            <div class="portlet-title">
                                <div class="caption">
                                    <i class="fa fa-gift"></i> THÔNG TIN CƠ BẢN
                                </div>

                            </div>
                            <div class="portlet-body form">
                                <form role="form" action="/customer/submit-profile" id="frmProfile" method="post">
                                    <div class="form-body">
                                        <div class="form-group">
                                            <label>Email</label>
                                            <input type="text" class="form-control" placeholder="Email Address"
                                                   value="<?php echo $this->customerInfo->{DbTable_Customer::COL_CUSTOMER_EMAIL} ?>"
                                                   readonly name="email">

                                        </div>
                                        <!-- <div class="form-group">
                                             <label for="exampleInputPassword1">Password</label>
                                             <div class="input-group">
                                                 <input type="password" class="form-control" id="exampleInputPassword1" placeholder="Password">
                                             <span class="input-group-addon">
                                             <i class="fa fa-user"></i>
                                             </span>
                                             </div>
                                         </div>-->
                                        <div class="form-group">
                                            <label>Số điện thoại</label>

                                            <div class="input-icon">
                                                <i class="fa fa-bell-o"></i>
                                                <input type="text" class="form-control" placeholder="Số điện thoại"
                                                       value="<?php echo $this->customerInfo->{DbTable_Customer::COL_CUSTOMER_PHONE} ?>" name="phone">
                                            </div>
                                        </div>

                                        <div class="row">

                                            <div class="col-md-6">
                                                <div class="form-group">
                                                    <label>Họ</label>
                                                    <input type="text"
                                                           value="<?php echo $this->customerInfo->{DbTable_Customer::COL_CUSTOMER_LAST_NAME} ?>"
                                                           class="form-control" name="last-name">
                                                </div>
                                            </div>
                                            <div class="col-md-6">
                                                <div class="form-group">
                                                    <label>Tên</label>
                                                    <input type="text"
                                                           value="<?php echo $this->customerInfo->{DbTable_Customer::COL_CUSTOMER_FIST_NAME} ?>"
                                                           class="form-control" name="first-name">
                                                </div>
                                            </div>

                                        </div>
                                        <div class="row">

                                            <div class="col-md-12">
                                                <div class="form-group">
                                                    <label>Địa chỉ</label>
                                                    <input type="text"
                                                           value="<?php echo $this->customerInfo->{DbTable_Customer::COL_CUSTOMER_ADDRESS} ?>"
                                                           class="form-control" name="address">
                                                </div>
                                            </div>

                                        </div>
                                        <div class="row">

                                            <div class="col-md-6">
                                                <div class="form-group">
                                                    <label>Tỉnh/thành</label>
                                                    <?php echo $this->formSelect(
                                                        'province',
                                                        $this->customerInfo->{DbTable_Customer::COL_FK_PROVINCE},
                                                        array(
                                                            'class' => 'form-control province',
                                                            'onchange' => 'CustomerInfo.showDistrictOptions(this.value);'
                                                        ),
                                                        $this->provinceData
                                                    ); ?>

                                                    <input type="hidden"
                                                           value="<?php echo $this->customerInfo->{DbTable_Customer::COL_FK_PROVINCE} ?>"
                                                           class="form-control" name="hidden-province">
                                                </div>
                                            </div>
                                            <div class="col-md-6">
                                                <div class="form-group">
                                                    <label>Quận/Huyện</label>
                                                    <?php echo $this->formSelect(
                                                        'district',
                                                        $this->customerInfo->{DbTable_Customer::COL_FK_DISTRICT},
                                                        array('class' => 'form-control district'),
                                                        $this->districtData
                                                    ); ?>
                                                    <input type="hidden"
                                                           value="<?php echo $this->customerInfo->{DbTable_Customer::COL_FK_DISTRICT} ?>"
                                                           class="form-control" name="hidden-district">

                                                </div>
                                            </div>
                                        </div>

                                        <div class="row">
                                            <div class="col-md-6">
                                                <div class="form-group">
                                                <img src="/captcha.jpg" id="captcha-image">
                                                </div>
                                            </div>
                                            <div class="col-md-6">
                                                <div class="form-group">
                                                <input type="text" value="" class="form-control" name="captcha"
                                                       id="captcha" title="Nhập mã xác nhận" placeholder="Mã xác nhận">
                                                 </div>
                                            </div>
                                            <div class="col-md-12">
                                                <p class="d_block">Mã xác nhận không rõ vui lòng nhấn vào <a
                                                        href="javascript:void(0)" id="refreshCaptcha"
                                                        class="f_bold">đây</a></p>
                                            </div>
                                        </div>


                                    </div>
                                    <div class="form-actions">
                                        <button type="submit" class="btn blue">Cập nhật</button>
                                     <!--   <button type="button" class="btn default">Cancel</button>-->
                                    </div>
                                </form>
                            </div>
                        </div>

                    </div>
                    <div class="col-sm-3">
                    </div>
                </div>

            </div>
        </div>
    </div>

    <script>
        districtJson = <?php echo json_encode(Model_District::getInstance()->getAll());?>;
    </script>

</div>