<!-- BEGIN PAGE HEADER-->
<div class="row">
    <div class="col-md-12">
        <!-- BEGIN PAGE TITLE & BREADCRUMB-->
        <h3 class="page-title">
            Quản lý slide - Thêm mới/ cập nhật slide
        </h3>
        <ul class="page-breadcrumb breadcrumb">
            <li>
                <i class="fa fa-home"></i>
                <a href="/">Home</a>
                <i class="fa fa-angle-right"></i>
            </li>
            <li>
                <a href="#">Thêm mới/ cập nhật slide</a>
            </li>
        </ul>
        <!-- END PAGE TITLE & BREADCRUMB-->
    </div>
</div>
<!-- END PAGE HEADER-->

<div class="row">
    <div class="col-md-12 ">
        <!-- BEGIN SAMPLE FORM PORTLET-->
        <div class="portlet box blue ">
            <div class="portlet-title">
                <div class="caption">
                    <i class="fa fa-gift"></i> Thông tin slide
                </div>
            </div>
            <div class="portlet-body form">
                <form class="form-horizontal" role="form" id="validate" enctype="multipart/form-data" method="post" target="ifrmEdit" action="<?php echo $this->adminUrl('site-slide/submit-edit'); ?>">
                    <div class="form-body">
                        <div class="form-group">
                            <label class="col-md-3 control-label">Tên<span class="required" aria-required="true"> * </span>:</label>
                            <div class="col-md-6">
                                <?php echo $this->formText(
                                    'name',
                                    $this->dataInfo ? $this->dataInfo->{DbTable_Site_Slide::COL_SITE_SLIDE_NAME} : null,
                                    array('class' => 'form-control validate[required]')
                                ); ?>
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-md-3 control-label">Hình ảnh<span class="required" aria-required="true"> * </span>:</label>
                            <div class="col-md-6">
                                <?php if ($this->dataInfo && $this->dataInfo->{DbTable_Site_Slide::COL_SITE_SLIDE_THUMBNAIL}) {
                                    echo $this->showImage($this->dataInfo->{DbTable_Site_Slide::COL_SITE_SLIDE_THUMBNAIL}, 150);
                                    echo '<br />';
                                } ?>
                                <input type="file" id="file_image" name="file_image" class="<?php echo $this->dataInfo? '' : 'validate[required]'; ?>" style="margin-top: 10px;"/>
                                <?php echo $this->formHidden(
                                    'image',
                                    $this->dataInfo ? $this->dataInfo->{DbTable_Site_Slide::COL_SITE_SLIDE_THUMBNAIL} : null
                                ); ?>
                            </div>

                        </div>

                        <div class="form-actions right">
                            <?php echo $this->formHidden(
                                'id',
                                $this->dataInfo ? $this->dataInfo->{DbTable_Site_Slide::COL_SITE_SLIDE_ID} : null
                            ); ?>

                            <button type="submit" class="btn green">Cập nhật</button>
                        </div>
                </form>
            </div>
        </div>
        <!-- END SAMPLE FORM PORTLET-->
    </div>
    <iframe name="ifrmEdit" id="ifrmEdit" style="display: none"></iframe>
</div>