
<section class="mt-none section-product">
    <div class="container">
        <div class="row">
            <div class="col-md-9">
                <div class="list-group-item active menu-category-name"
                     style="width: 100%; margin-bottom: 20px; margin-top: 20px; font-size: 18px;">Quá
                    trình phát triển</div>

                <ul class="timeline">
                    <li class="timeline-yellow">
                        <div class="timeline-time">
                            <span class="date"> 25/03/2016 </span> <span class="time">
									18:30 </span>
                        </div>
                        <div class="timeline-icon">
                            <i class="fa fa-trophy"></i>
                        </div>
                        <div class="timeline-body">
                            <h2>Ngày thành lập nhóm phát triển website</h2>
                            <div class="timeline-content">
                                <img class="timeline-img pull-left" src="<?php echo HOST_STATIC_DEFAULT;?>/img/about/build.jpg"
                                     alt=""> 4 thành viên đã họp mặt và thành lập nhóm
                                LN3.
                            </div>
                            <div class="timeline-footer">
                                <a href="#" class="nav-link pull-right"> <i
                                        class="m-icon-swapright m-icon-white"></i>
                                </a>
                            </div>
                        </div>
                    </li>
                    <li class="timeline-blue">
                        <div class="timeline-time">
                            <span class="date"> 1/11/2016 </span> <span class="time">
									12:04 </span>
                        </div>
                        <div class="timeline-icon">
                            <i class="fa fa-video-camera"></i>
                        </div>
                        <div class="timeline-body">
                            <h2>Lên kế hoạch xây dựng website</h2>
                            <div class="timeline-content">
                                <img class="timeline-img pull-right"
                                     src="<?php echo HOST_STATIC_DEFAULT;?>/img/about/scheduling.jpg" alt=""> Lập kế hoạch, dự
                                trù các công việc cần thực hiện
                            </div>
                            <div class="timeline-footer">
                                <a href="#" class="nav-link"> <i
                                        class="m-icon-swapright m-icon-white"></i>
                                </a>
                            </div>
                        </div>
                    </li>
                    <li class="timeline-green">
                        <div class="timeline-time">
                            <span class="date"> 02/11/2016 </span> <span class="time">
									05:36 </span>
                        </div>
                        <div class="timeline-icon">
                            <i class="fa fa-comments"></i>
                        </div>
                        <div class="timeline-body">
                            <h2>Thực hiện dự án</h2>
                            <div class="timeline-content">
                                <img class="timeline-img pull-left" src="<?php echo HOST_STATIC_DEFAULT;?>/img/about/work.jpg"
                                     alt=""> Phân chia công việc cụ thể cho từng thành viên
                                trong nhóm.
                            </div>
                            <div class="timeline-footer">
                                <a href="#" class="nav-link"> <i
                                        class="m-icon-swapright m-icon-white"></i>
                                </a>
                            </div>
                        </div>
                    </li>
                    <li class="timeline-red">
                        <div class="timeline-time">
                            <span class="date"> 15/11/2016 </span> <span class="time">
									0:0 </span>
                        </div>
                        <div class="timeline-icon">
                            <i class="fa fa-rss"></i>
                        </div>
                        <div class="timeline-body">
                            <h2>Triển khai dự án</h2>
                            <div class="timeline-content">
                                <img class="timeline-img pull-left" src="<?php echo HOST_STATIC_DEFAULT;?>/img/about/deploy.jpg"
                                     alt=""> Sau nhiều ngày tháng bắt tay vào công việc. ngày
                                15/11/2016. LN3 đã đưa dự án lên hệ thống. Website chạy bản thử nghiệm.
                            </div>
                            <div class="timeline-footer"></div>
                        </div>
                    </li>
                    <li class="timeline-grey">
                        <div class="timeline-time">
                            <span class="date"> 28/12/2016 </span> <span class="time">
									12:00 </span>
                        </div>
                        <div class="timeline-icon">
                            <i class="fa fa-times"></i>
                        </div>
                        <div class="timeline-body">
                            <h2>Triển khai chính thức</h2>
                            <div class="timeline-content">Dự án tập hợp các tin tức nhà trọ chính thức hoạt động</div>
                            <div class="timeline-footer">
                                <a href="#" class="nav-link pull-right"> <i
                                        class="m-icon-swapright m-icon-white"></i>
                                </a>
                            </div>
                        </div>
                    </li>

                </ul>

            </div>
            <div class="col-md-3">

                <div class="" style="margin-top: 20px;">
                    <div class="list-group-item active menu-category-name"
                         style="width: 280px; margin-bottom: 20px;">Fan page</div>
                    <div class="fb-page"
                         data-href="https://www.facebook.com/XHome-Pho%CC%80ng-Tro%CC%A3-1212428578819117/"
                         data-hide-cover="false" data-show-facepile="true"
                         data-show-posts="false">
                        <div class="fb-xfbml-parse-ignore">
                            <blockquote cite="https://www.facebook.com/XHome-Pho%CC%80ng-Tro%CC%A3-1212428578819117/">
                                <a href="https://www.facebook.com/XHome-Pho%CC%80ng-Tro%CC%A3-1212428578819117/"> &amp;
                                    Nhà trọ sinh viên sài gòn</a>
                            </blockquote>
                        </div>
                    </div>

                </div>
            </div>

        </div>
        <h2 class="title">Thành viên</h2>
        <div class="row front-team">
            <ul class="list-unstyled">
                <li class="col-md-3">
                    <div class="thumbnail">
                        <img alt="" src="<?php echo HOST_STATIC_DEFAULT;?>/img/about/TTL.jpg" style="height:300px;">


                    </div>
                    <div class="description">
                        <h3>
                            <strong>TTL</strong> <small>Nghiên cứu - cố vấn</small>
                        </h3>
                        <p>Phân tích, hỗ trợ định hướng phát triển dự án</p>
                    </div>
                </li>
                <li class="col-md-3">
                    <div class="thumbnail">
                        <img alt="Nguyễn Văn Trọng Nhân" src="http://static.nguyennhan09cntt.ln3.in/statics/asset/default/img/nguyennhan09cntt.jpg" width="100%" title="Nguyễn Văn Trọng Nhân" style="height:300px;">


                    </div>
                    <div class="description">
                        <h3>
                            <strong>Nguyễn Văn Trọng Nhân</strong>
                        </h3>
                        <p class="mb-none">Project Manager</p>
                        <p>Phân tích thiết kế - xây dựng dự án... <a href="http://nguyennhan09cntt.ln3.in" target="_blank">Xem thêm</a></p>
                    </div>
                </li>
                <li class="col-md-3">
                    <div class="thumbnail">
                        <img alt="" src="<?php echo HOST_STATIC_DEFAULT;?>/img/about/LPN.jpg" style="height:300px;">

                    </div>
                    <div class="description">
                        <h3>
                            <strong>LPN</strong> <small>Nghiên cứu - cố vấn</small>
                        </h3>
                        <p>Phân tích, hỗ trợ định hướng phát triển dự án</p>
                    </div>
                </li>
                <li class="col-md-3">
                    <div class="thumbnail">
                        <img alt="" src="<?php echo HOST_STATIC_DEFAULT;?>/img/about/LVN.jpg" style="height:300px;">

                    </div>
                    <div class="description">
                        <h3>
                            <strong>LVN</strong> <small>Quản trị hệ thống</small>
                        </h3>
                        <p>Quản lí, bảo trì hệ thống , vận hành và cải tiến...</p>
                    </div>
                </li>
            </ul>
        </div>


    </div>
</section>


