<!-- BEGIN PAGE HEADER-->
<div class="row">
    <div class="col-md-12">
        <!-- BEGIN PAGE TITLE & BREADCRUMB-->
        <h3 class="page-title">
            Administration - Quản lý phân quyền
        </h3>
        <ul class="page-breadcrumb breadcrumb">
            <li>
                <i class="fa fa-home"></i>
                <a href="/">Home</a>
                <i class="fa fa-angle-right"></i>
            </li>
            <li>
                <a href="#">Quản lý phân quyền</a>
            </li>
        </ul>
        <!-- END PAGE TITLE & BREADCRUMB-->
    </div>
</div>

<div class="row">
    <div class="col-md-12">
        <!-- BEGIN EXAMPLE TABLE PORTLET-->
        <div class="portlet box grey-cascade">
            <div class="portlet-title">
                <div class="caption">
                    <i class="fa fa-globe"></i><?php echo $this->pagination->getTotalItemCount(); ?> dòng(s)
                </div>
                <div class="actions">
                    <div class="item-actions">
                        <label>Cập nhật hàng loạt:</label>
                        <select id="manualUpdateElement">
                            <option value="">Chọn một hành động...</option>
                            <option value="activate">Active</option>
                            <option value="inactivate">Inactive</option>>
                            <option value="display">Hiển thị</option>
                            <option value="non-display">Không hiển thị</option>
                        </select>
                    </div>
                </div>

            </div>
            <div class="portlet-body">
                <div class="table-toolbar">
                    <div class="btn-group">
                        <button id="btn_add_new" class="btn green">
                            Thêm mới <i class="fa fa-plus"></i>
                        </button>
                    </div>
                    <div class="pull-right">
                        <form method="get" action="">
                            <fieldset class="filter">
                                <?php echo $this->formSelect(
                                    'r',
                                    $this->fkResource,
                                    array('class' =>'input-inline form-control'),
                                    array(0 => '++') + $this->resourceData
                                ); ?>
                                <input type="submit" value="Tìm kiếm" class="btn blue" />
                            </fieldset>

                        </form>
                    </div>
                </div>
                <table class="table table-striped table-bordered table-hover" id="table_privilege">
                    <thead>
                    <tr>
                        <th class="table-checkbox">
                            <input type="checkbox" class="group-checkable" data-set="#table_privilege .checkboxes"/>
                        </th>
                        <th>Tên phân quyền</th>
                        <th>Resource</th>
                        <th>Action</th>
                        <th>Tình trạng</th>
                        <th>Thứ tự</th>
                        <th>Hiển thị</th>
                        <th>Ngày tạo</th>
                        <th></th>
                    </tr>
                    </thead>
                    <tbody>
                    <?php foreach ($this->pagination as $data) {?>
                        <tr>
                            <td>
                                <?php echo $this->formCheckbox(
                                    null,
                                    $data->{DbTable_Admin_Privilege::COL_ADMIN_PRIVILEGE_ID},
                                    array('class' => 'checkboxes')
                                ); ?>
                            </td>
                            <td><?php echo $data->{DbTable_Admin_Privilege::COL_ADMIN_PRIVILEGE_NAME}; ?></td>
                            <td><?php echo $data->{DbTable_Admin_Resource::COL_ADMIN_RESOURCE_NAME}; ?></td>
                            <td><?php echo $data->{DbTable_Admin_Privilege::COL_ADMIN_PRIVILEGE_ACTION}; ?></td>
                            <td>
                                <?php echo $this->activeLabel($data->{DbTable_Admin_Privilege::COL_ADMIN_PRIVILEGE_ACTIVE}); ?>
                            </td>
                            <td><?php echo $data->{DbTable_Admin_Privilege::COL_ADMIN_PRIVILEGE_PRIORITY}; ?></td>
                            <td align="center">
                                <?php if ($data->{DbTable_Admin_Privilege::COL_ADMIN_PRIVILEGE_DISPLAY}==Application_Constant_Db_Admin_Resource::DISPLAY) { ?>
                                    <i class="fa fa-check font-green"></i>
                                <? } ?>
                            </td>
                            <td><?php echo $data->{DbTable_Admin_Privilege::COL_ADMIN_PRIVILEGE_CREATED_AT}; ?></td>
                            <td>
                                <a href="<?php echo $this->adminUrl('admin-privilege/edit/'); ?>?i=<?php echo $data->{DbTable_Admin_Privilege::COL_ADMIN_PRIVILEGE_ID}; ?>" title="Update" class="btn default btn-xs purple"><i class="fa fa-edit"></i> Chỉnh sủa</a>
                            </td>
                        </tr>
                    <?php } ?>
                    </tbody>
                    <tfoot>
                    <tr>
                        <td colspan="99">
                            <?php echo $this->pagination; ?>
                        </td>
                    </tr>
                    </tfoot>
                </table>

            </div>
        </div>
        <!-- END EXAMPLE TABLE PORTLET-->
    </div>
</div>