<ul class="list-unstyled profile-nav mt-md">
    <li  class="center">
        <span class="img-thumbnail" style="width:100%;">
            <img src="http://xome.ln3.in/upload/default/no-images.png" class="img-responsive" alt="">
        </span>


    </li>
    <li>
        <a href="/tai-khoan/thong-tin.html">
            Thông tin </a>
    </li>
    <!--<li>
        <a href="/tai-khoan/danh-sach-lop-nhan.html">
            Lớp học đã nhận dạy</a>
    </li>-->
    <li>
        <a href="/tai-khoan/danh-sach-tin-nha-tro.html">
            Tin đã đăng<!--<span>
												3 </span>-->
        </a>
    </li>

    <!--<li>
        <a href="/tai-khoan/khoa-hoc-cua-toi.html">
            Khóa học đăng ký học</a>
    </li>-->
    <li>
        <a href="/tai-khoan/dang-xuat" style="  background: #58ace4;color:#f2f2f2; ">
            Đăng xuất </a>
    </li>
</ul>