<!-- BEGIN PAGE HEADER-->
<div class="row">
    <div class="col-md-12">
        <!-- BEGIN PAGE TITLE & BREADCRUMB-->
        <h3 class="page-title">
            Administration - Danh sách quản trị viên
        </h3>
        <ul class="page-breadcrumb breadcrumb">
            <li>
                <i class="fa fa-home"></i>
                <a href="/">Home</a>
                <i class="fa fa-angle-right"></i>
            </li>
            <li>
                <a href="#">Danh sách quản trị viên</a>
            </li>
        </ul>
        <!-- END PAGE TITLE & BREADCRUMB-->
    </div>
</div>

<div class="row">
    <div class="col-md-12">
        <!-- BEGIN EXAMPLE TABLE PORTLET-->
        <div class="portlet box grey-cascade">
            <div class="portlet-title">
                <div class="caption">
                    <i class="fa fa-globe"></i><?php echo $this->pagination->getTotalItemCount(); ?> dòng(s)
                </div>
                <div class="actions">
                    <div class="item-actions">
                        <label>Cập nhật hàng loạt:</label>
                        <select id="manualUpdateElement">
                            <option value="">Chọn một hành động...</option>
                            <option value="activate">Active</option>
                            <option value="inactivate">Inactive</option>>
                            <option value="display">Hiển thị</option>
                            <option value="non-display">Không hiển thị</option>
                        </select>
                    </div>
                </div>

            </div>
            <div class="portlet-body">
                <div class="table-toolbar">
                    <div class="btn-group">
                        <button id="btn_add_new" class="btn green">
                            Thêm mới <i class="fa fa-plus"></i>
                        </button>
                    </div>
                    <div class="pull-right">
                        <form method="get" action="">
                            <fieldset class="filter">
                                <?php echo $this->formText('e', $this->username, array('size' => 40, 'placeholder' => 'Email đăng nhập', 'class' =>'input-inline form-control')); ?>
                                <?php echo $this->formSelect(
                                    'r',
                                    $this->fkRole,
                                    array('class' =>'input-inline form-control'),
                                    array(0 => '++') + $this->roleData
                                ); ?>
                                <input type="submit" value="Tìm kiếm" class="btn blue" />
                            </fieldset>

                        </form>
                    </div>
                </div>
                <table class="table table-striped table-bordered table-hover" id="table_admin">
                    <thead>
                    <tr>
                        <th class="table-checkbox">
                            <input type="checkbox" class="group-checkable" data-set="#table_admin .checkboxes"/>
                        </th>
                        <td>Email</td>
                        <td>Họ và tên</td>
                        <td>Nhóm quản trị</td>
                        <td>Đăng nhập lần cuối</td>
                        <td>IP đăng nhập</td>
                        <td>Tình trạng</td>
                        <td>Ngày tạo</td>
                        <td></td>
                    </tr>
                    </thead>
                    <tbody>
                    <?php foreach ($this->pagination as $data) {?>
                        <tr>
                            <td>
                                <?php echo $this->formCheckbox(
                                    null,
                                    $data->{DbTable_Admin::COL_ADMIN_ID},
                                    array('class' => 'checkboxes')
                                ); ?>
                            </td>
                            <td><?php echo $data->{DbTable_Admin::COL_ADMIN_EMAIL}; ?></td>
                            <td><?php echo $data->{DbTable_Admin::COL_ADMIN_FULLNAME}; ?></td>
                            <td><?php echo $data->{DbTable_Admin_Role::COL_ADMIN_ROLE_NAME}; ?></td>
                            <td><?php echo $data->{DbTable_Admin::COL_ADMIN_LAST_LOGIN}; ?></td>
                            <td><?php echo $data->{DbTable_Admin::COL_ADMIN_LAST_LOGIN_IP}; ?></td>
                            <td><?php echo $this->activeLabel($data->{DbTable_Admin::COL_ADMIN_ACTIVE}); ?></td>
                            <td><?php echo $data->{DbTable_Admin::COL_ADMIN_CREATED_AT}; ?></td>
                            <td>
                                <a href="<?php echo $this->adminUrl('admin/edit/'); ?>?i=<?php echo $data->{DbTable_Admin::COL_ADMIN_ID}; ?>">Edit</a>
                            </td>
                        </tr>
                    <?php } ?>
                    </tbody>
                    <tfoot>
                    <tr>
                        <td colspan="99">
                            <?php echo $this->pagination; ?>
                        </td>
                    </tr>
                    </tfoot>
                </table>

            </div>
        </div>
        <!-- END EXAMPLE TABLE PORTLET-->
    </div>
</div>