<!-- BEGIN PAGE HEADER-->
<div class="row">
    <div class="col-md-12">
        <!-- BEGIN PAGE TITLE & BREADCRUMB-->
        <h3 class="page-title">
            Administration - Danh sách quản trị viên
        </h3>
        <ul class="page-breadcrumb breadcrumb">
            <li>
                <i class="fa fa-home"></i>
                <a href="/">Home</a>
                <i class="fa fa-angle-right"></i>
            </li>
            <li>
                <a href="#">Danh sách quản trị viên</a>
            </li>
        </ul>
        <!-- END PAGE TITLE & BREADCRUMB-->
    </div>
</div>

<div class="row">
    <div class="col-md-12 ">
        <!-- BEGIN SAMPLE FORM PORTLET-->
        <div class="portlet box blue ">
            <div class="portlet-title">
                <div class="caption">
                    <i class="fa fa-gift"></i> Thông tin quản trị viên
                </div>
            </div>
            <div class="portlet-body form">
                <form class="form-horizontal" role="form" id="validate" method="post" target="ifrmEdit" action="<?php echo $this->adminUrl('admin/submit-edit-info'); ?>">
                    <div class="form-body">
                        <div class="form-group">
                            <label class="col-md-3 control-label">Email <span class="required" aria-required="true"> * </span>:</label>
                            <div class="col-md-6">
                                <?php
                                    echo $this->dataInfo->{DbTable_Admin::COL_ADMIN_EMAIL};
                                    echo $this->formHidden(
                                        'email',
                                        $this->dataInfo->{DbTable_Admin::COL_ADMIN_EMAIL}
                                    );
                                ?>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-md-3 control-label">Họ và Tên:<span class="required" aria-required="true"> * </span>:</label>
                            <div class="col-md-6">
                                <?php echo $this->formText(
                                    'fullName',
                                    $this->dataInfo ? $this->dataInfo->{DbTable_Admin::COL_ADMIN_FULLNAME} : null,
                                    array('class' => 'form-control validate[required]')
                                ); ?>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-md-3 control-label">Mật khẩu cũ:<span class="required" aria-required="true"> * </span>:</label>
                            <div class="col-md-6">
                                <?php
                                    echo $this->formPassword(
                                        'password',
                                        null,
                                        array('class' => 'form-control validate[required]')
                                    );
                                ?>
                            </div>

                        </div>
                        <div class="form-group">
                            <label class="col-md-3 control-label">Mật khẩu mới:<span class="required" aria-required="true"> * </span>:</label>
                            <div class="col-md-6">
                                <?php
                                    echo $this->formPassword(
                                        'new-password',
                                        null,
                                        array('class' => 'form-control validate[required]')
                                    );
                                ?>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-md-3 control-label">Xác nhận mật khẩu mới::<span class="required" aria-required="true"> * </span>:</label>
                            <div class="col-md-6">
                                <?php
                                    echo $this->formPassword(
                                        're-new-password',
                                        null,
                                        array('class' => 'form-control validate[required]')
                                    );
                                ?>
                            </div>

                        </div>




                        <div class="form-actions right">
                            <?php echo $this->formHidden(
                                'id',
                                $this->dataInfo ? $this->dataInfo->{DbTable_Admin::COL_ADMIN_ID} : null
                            ); ?>

                            <button type="submit" class="btn green">Cập nhật</button>
                        </div>
                </form>
            </div>
        </div>
        <!-- END SAMPLE FORM PORTLET-->
    </div>
    <iframe name="ifrmEdit" id="ifrmEdit" style="display: none"></iframe>
</div>