<? if($this->isError){ ?>
    <div class="wrapper">
        <div class="nNote nFailure hideit">
            <p>
                <? if($this->isError==Application_Constant_Module_Admin_Login_ForgotPassword::ERROR_CODE_EMAIL_NULL){ ?>
                    Vui lòng cung cấp email đăng ký
                <? } elseif ($this->isError==Application_Constant_Module_Admin_Login_ForgotPassword::ERROR_CODE_EMAIL_INVALID) { ?>
                    Email đăng ký không tồn tại trong hệ thống. Mời bạn nhập lại.
                <? } elseif($this->isError==Application_Constant_Module_Admin_Login_ForgotPassword::ERROR_CODE_SUCCESSFUL) { ?>
                    Một mật khẩu truy cập mới đã được gửi đến email đăng ký của bạn. Mời bạn kiểm tra email.
                <? } ?>
            </p>
        </div>
    </div>
<? } ?>
<div class="loginWrapper">
    <div class="loginLogo"><img src="images/logo.png" alt="" /></div>
    <div class="widget">
        <div class="title"><img src="images/icons/dark/files.png" alt="" class="titleIcon" /><h6>Quên mật khẩu</h6></div>
        <form action="/login/submit-forgot-password" id="validate" class="form">
            <fieldset>
                <div class="formRow">
                    <label for="login">Email:</label>
                    <div class="loginInput"><input type="text" name="email" class="validate[required]" id="login" /></div>
                    <div class="clear"></div>
                </div>
                <div class="loginControl">
                    <input type="submit" value="Nhận lại mật khẩu" class="dredB logMeIn" />
                    <div class="clear"></div>
                </div>
            </fieldset>
        </form>
    </div>
</div>