<!-- BEGIN PAGE HEADER-->
<div class="row">
    <div class="col-md-12">
        <!-- BEGIN PAGE TITLE & BREADCRUMB-->
        <h3 class="page-title">
            Quản lý Celebrity - Thêm mới/Cập nhật Celebrity
        </h3>
        <ul class="page-breadcrumb breadcrumb">
            <li>
                <i class="fa fa-home"></i>
                <a href="/">Home</a>
                <i class="fa fa-angle-right"></i>
            </li>
            <li>
                Thêm mới/Cập nhật Celebrity
            </li>
        </ul>
        <!-- END PAGE TITLE & BREADCRUMB-->
    </div>
</div>



<div class="row">
    <div class="col-md-12 ">
        <!-- BEGIN SAMPLE FORM PORTLET-->
        <div class="portlet box blue ">
            <div class="portlet-title">
                <div class="caption">
                    <i class="fa fa-gift"></i> Thông tin Celebrity
                </div>
            </div>
            <div class="portlet-body form">
                <form class="form-horizontal" role="form" id="validate" enctype="multipart/form-data" method="post" target="ifrmEdit" action="<?php echo $this->adminUrl('celebrity/submit-edit'); ?>">
                    <div class="form-body">
                        <div class="form-group">
                            <label class="col-md-3 control-label">Tên Celebrity:<span class="required" aria-required="true"> * </span>:</label>
                            <div class="col-md-6">
                                <?php echo $this->formText(
                                    'name',
                                    $this->dataInfo ? $this->dataInfo->{DbTable_Celebrity::COL_CELEBRITY_NAME} : null,
                                    array('class' => 'form-control validate[required]')
                                ); ?>
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-md-3 control-label">Link facebook:</label>
                            <div class="col-md-6">
                                <?php echo $this->formText(
                                    'faceBook',
                                    $this->dataInfo ?  $this->dataInfo->{DbTable_Celebrity::COL_CELEBRITY_FACEBOOK_URL} : null,
                                    array('class' => 'form-control')
                                );?>
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-md-3 control-label">Hình đại diện<span class="required" aria-required="true"> * </span>:</label>
                            <div class="col-md-6">
                                <?php if ($this->dataInfo && $this->dataInfo->{DbTable_Celebrity::COL_CELEBRITY_THUMB_NAIL}) {
                                    echo $this->showImage($this->dataInfo->{DbTable_Celebrity::COL_CELEBRITY_THUMB_NAIL}, 150);
                                    echo '<br />';
                                } ?>
                                <input type="file" id="file_image" name="file_image" class="margin-top-20">
                                <?php echo $this->formHidden(
                                    'image',
                                    $this->dataInfo ? $this->dataInfo->{DbTable_Celebrity::COL_CELEBRITY_THUMB_NAIL} : null
                                ); ?>
                            </div>
                        </div>



                        <div class="form-group">
                            <label class="col-md-3 control-label">Danh mục:<span class="required" aria-required="true"> * </span>:</label>
                            <div class="col-md-6">
                                <?php echo $this->formSelect(
                                    'category',
                                    $this->dataInfo ? $this->dataInfo->{DbTable_Celebrity::COL_FK_CELEBRITY_CATEGORY} : null,
                                    array('class' => 'celebrityCategory validate[required] form-control'),
                                    array('' => '++') + $this->categoryData
                                ); ?>
                                <?php echo $this->formHidden(
                                    'hiddenCelebrityCategory',
                                    $this->dataInfo ? $this->dataInfo->{DbTable_Celebrity::COL_FK_CELEBRITY_CATEGORY} : null
                                ); ?>
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-md-3 control-label">Giới tính:<span class="required" aria-required="true"> * </span>:</label>
                            <div class="col-md-6">
                                <?php echo $this->formSelect(
                                    'gender',
                                    $this->dataInfo ? $this->dataInfo->{DbTable_Celebrity::COL_CELEBRITY_GENDER} : null,
                                    array('class' => 'gender validate[required] form-control'),
                                    array(1 => 'Nam', 2 => 'Nữ')
                                ); ?>

                            </div>
                        </div>


                        <div class="form-group">
                            <label class="col-md-3 control-label">Tỉnh/Thành:<span class="required" aria-required="true"> * </span>:</label>
                            <div class="col-md-6">
                                <?php echo $this->formSelect(
                                    'province',
                                    $this->dataInfo ? $this->dataInfo->{DbTable_Celebrity::COL_FK_PROVICE} : null,
                                    array('class' => 'province validate[required] form-control'),
                                    array('' => '++') + $this->provinceData
                                ); ?>
                                <?php echo $this->formHidden(
                                    'hiddenProvince',
                                    $this->dataInfo ? $this->dataInfo->{DbTable_Celebrity::COL_FK_PROVICE} : null
                                ); ?>
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-md-3 control-label">Quận/Huyện:</label>
                            <div class="col-md-6">
                                <?php echo $this->formSelect(
                                    'district',
                                    $this->dataInfo ? $this->dataInfo->{DbTable_Celebrity::COL_FK_DISTRICT} : null,
                                    array('class' => 'district form-control'),
                                    array('' => '++')
                                ); ?>
                                <?php echo $this->formHidden(
                                    'hiddenDistrict',
                                    $this->dataInfo ? $this->dataInfo->{DbTable_Celebrity::COL_FK_DISTRICT} : null
                                ); ?>
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-md-3 control-label">Mô tả:</label>
                            <div class="col-md-9">
                                <?php echo $this->formTextarea(
                                    'shortDescription',
                                    $this->dataInfo ? $this->dataInfo->{DbTable_Celebrity::COL_CELEBRITY_DESCRIPTION} : null,
                                    array('rows' => 3)
                                ); ?>
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-md-3 control-label">Thông tin chi tiết:</label>
                            <div class="col-md-9">
                                <?php echo $this->formTextarea(
                                    'description',
                                    $this->dataInfo ? $this->dataInfo->{DbTable_Celebrity::COL_CELEBRITY_CONTENT} : null,
                                    array('rows' => 3)
                                ); ?>
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-md-3 control-label">Tags:</label>
                            <div class="col-md-6">
                                <?php echo $this->formText(
                                    'tag',
                                    $this->dataInfo ?  $this->dataInfo->{DbTable_Celebrity::COL_CELEBRITY_TAG} : null,
                                    array('class' => 'form-control')
                                );?>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-md-3 control-label">Ghi chú:</label>
                            <div class="col-md-6">
                                <?php echo $this->formTextarea(
                                    'note',
                                    $this->dataInfo ? $this->dataInfo->{DbTable_Celebrity::COL_CELEBRITY_NOTE} : null,
                                    array('rows' => 3)
                                ); ?>
                            </div>
                        </div>


                        <div class="form-actions right">
                            <?php echo $this->formHidden(
                                'id',
                                $this->dataInfo ? $this->dataInfo->{DbTable_Celebrity::COL_CELEBRITY_ID} : null
                            ); ?>
                            <?php echo $this->formHidden(
                                'componentId',
                                1
                            ); ?>
                            <button type="submit" class="btn green">Cập nhật</button>
                        </div>
                </form>
            </div>
        </div>
        <!-- END SAMPLE FORM PORTLET-->
    </div>
    <iframe name="ifrmEdit" id="ifrmEdit" style="display: none"></iframe>
</div>

<script>
    var districtJson = <?php echo json_encode(Admin_Model_District::getInstance()->getAll());?>;
</script>