<!-- BEGIN PAGE HEADER-->
<div class="row">
    <div class="col-md-12">
        <!-- BEGIN PAGE TITLE & BREADCRUMB-->
        <h3 class="page-title">
            Quản lý Celebrity - Danh sách Celebrity
        </h3>
        <ul class="page-breadcrumb breadcrumb">
            <li>
                <i class="fa fa-home"></i>
                <a href="/">Home</a>
                <i class="fa fa-angle-right"></i>
            </li>
            <li>
                Danh sách sản phẩm
            </li>
        </ul>
        <!-- END PAGE TITLE & BREADCRUMB-->
    </div>
</div>

<div class="row">
    <div class="col-md-12">
        <!-- BEGIN EXAMPLE TABLE PORTLET-->
        <div class="portlet box grey-cascade">
            <div class="portlet-title">
                <div class="caption">
                    <i class="fa fa-globe"></i><?php echo $this->pagination->getTotalItemCount(); ?> dòng(s)
                </div>
                <div class="actions">
                    <div class="item-actions">
                        <label>Cập nhật hàng loạt:</label>
                        <select id="manualUpdateElement">
                            <option value="">Chọn hành động...</option>
                            <option value="activate">Active</option>
                            <option value="inactivate">Inactive</option>>
                        </select>
                    </div>
                </div>

            </div>
            <div class="portlet-body">
                <div class="table-toolbar">
                    <div class="btn-group">
                        <button id="btn_add_new" class="btn green">
                            Thêm mới <i class="fa fa-plus"></i>
                        </button>
                    </div>
                    <div class="pull-right margin-bottom-15">
                        <form method="get" action="">
                            <fieldset class="filter">
                                <?php echo $this->formText('n', $this->name, array('size' => 30, 'placeholder' => 'Tên celebrity', 'class'=>'input-inline form-control')); ?>
                                <?php echo $this->formText('e', $this->code, array('size' => 30, 'placeholder' => 'Mã celebrity', 'class'=>'input-inline form-control')); ?>
                                <?php echo $this->formSelect(
                                    'a',
                                    $this->active,
                                    array('class'=>'input-inline form-control'),
                                    array('-1' => 'Tình trạng') + $this->activeValue()
                                ); ?>
                                <?php echo $this->formSelect(
                                    'p',
                                    $this->priority,
                                    array('class'=>'input-inline form-control'),
                                    array(
                                        '-1' => 'Hiển thị',
                                        '0' => 'Không ưu tiên',
                                        '1' => 'Ưu tiên'
                                    )
                                ); ?>
                                <input type="submit" value="Tìm kiếm" class="btn blue" />

                            </fieldset>

                        </form>
                    </div>
                </div>
                <table class="table table-striped table-bordered table-hover" id="table_product">
                    <thead>
                    <tr>
                        <th class="table-checkbox">
                            <input type="checkbox" class="group-checkable" data-set="#table_product .checkboxes"/>
                        </th>
                        <th>Mã Celebrity</th>

                        <th>Hình ảnh</th>
                        <th>Tên Celebrity</th>
                        <th>Giới tính</th>
                        <th>Danh mục</th>
                        <th>Ưu tiên</th>
                        <th>Tình trạng</th>
                        <th>Ngày tạo</th>
                        <th width="90"></th>
                    </tr>
                    </thead>
                    <tbody>

                    <?php foreach ($this->pagination as $data) {?>
                        <tr>
                            <td>
                                <?php echo $this->formCheckbox(
                                    null,
                                    $data->{DbTable_Celebrity::COL_CELEBRITY_ID},
                                    array('class' => 'checkboxes',)
                                ); ?>
                            </td>
                            <td><?php echo $this->celebrityEncode($data->{DbTable_Celebrity::COL_CELEBRITY_ID}); ?></td>

                            <td align="center"><?php echo $this->showImage($data->{DbTable_Celebrity::COL_CELEBRITY_THUMB_NAIL}, 150); ?></td>
                            <td><?php echo $data->{DbTable_Celebrity::COL_CELEBRITY_NAME}; ?></td>
                            <td><?php echo $this->genderLabel($data->{DbTable_Celebrity::COL_CELEBRITY_GENDER}); ?></td>
                            <td><?php echo $this->celebrityCategoryLabel($data->{DbTable_Celebrity::COL_FK_CELEBRITY_CATEGORY}); ?></td>
                            <td align="center" width="90"><?php echo $data->{DbTable_Celebrity::COL_CELEBRITY_PRIORITY} ? ' <i class="fa fa-check font-green"></i>' : ''; ?></td>
                            <td><?php echo $this->activeLabel($data->{DbTable_Celebrity::COL_FK_CONFIG_STATUS}); ?></td>
                            <td><?php echo $data->{DbTable_Celebrity::COL_CELEBRITY_CREATED_AT}; ?></td>
                            <td>
                                <a href="<?php echo $this->adminUrl('celebrity/edit/'); ?>?i=<?php echo $data->{DbTable_Celebrity::COL_CELEBRITY_ID}; ?>">Cập nhật</a>
                                <br>
                                <a href="<?php echo $this->adminUrl('celebrity-image/'); ?>?p=<?php echo $data->{DbTable_Celebrity::COL_CELEBRITY_ID}; ?>" target="_blank">Hình ảnh</a>
                            </td>
                        </tr>
                    <?php } ?>
                    </tbody>
                    <tfoot>
                    <tr>
                        <td colspan="99">
                            <?php echo $this->pagination; ?>
                        </td>
                    </tr>
                    </tfoot>
                </table>

            </div>
        </div>
        <!-- END EXAMPLE TABLE PORTLET-->
    </div>
</div>