<p><strong>Kính Gửi Quý Khách Hàng,</strong></p>

<p>Cảm ơn quý khách đã dành thời gian làm khảo sát tại Pasoto.com</p>
<p>Ý kiến của quý khách rất quan trọng trong việc nâng cao chất lượng phục vụ quý khách hàng trong thời gian tới. Chúng tôi ghi nhận tất cả các ý kiến và sẽ cải thiện trong thời gian ngắn nhất.</p>
<p>Mã voucher của quý khách là: <strong>%voucher_code%</strong></p>
<p><em>  Có giá trị giảm 50.000đ cho đơn hàng từ 200.000đ trở lên</em></p>
<p><em>  Hạn sử dụng: trong vòng 3 tháng kể từ ngày nhận voucher.</em></p>
<p><em>  Áp dụng cho tất cả các tuyến đường và chuyến xe</em></p>

<p>Qúy khách có thể xem thêm các chương trình khuyến mãi khác <a href="https://pasoto.com/uu-dai/khuyen-mai-moi-nhat.html?utm_source=Email&utm_medium=marketing&utm_campaign=khaosat">tại đây</a>
Hoặc gửi <a href="https://pasoto.com/tin-tuc/pasoto-khao-sat-khach-hang/?utm_source=Email&utm_medium=marketing&utm_campaign=khaosat">khảo sát này</a> đến bạn bè của mình giúp Pasoto nhé.</p>

<p>Trân Trọng</p>
