<!-- BEGIN PAGE HEADER-->
<div class="row">
    <div class="col-md-12">
        <!-- BEGIN PAGE TITLE & BREADCRUMB-->
        <h3 class="page-title">
            Quản lý khuyến mãi - Danh sách khuyến mãi
        </h3>
        <ul class="page-breadcrumb breadcrumb">
            <li>
                <i class="fa fa-home"></i>
                <a href="/">Home</a>
                <i class="fa fa-angle-right"></i>
            </li>
            <li>
                Danh sách khuyến mãi
            </li>
        </ul>
        <!-- END PAGE TITLE & BREADCRUMB-->
    </div>
</div>


<div class="row">
    <div class="col-md-12 ">
        <!-- BEGIN SAMPLE FORM PORTLET-->
        <div class="portlet box blue ">
            <div class="portlet-title">
                <div class="caption">
                    <i class="fa fa-gift"></i> Thông tin khuyến mãi
                </div>
            </div>
            <div class="portlet-body form">
                <form class="form-horizontal" role="form" id="validate" enctype="multipart/form-data" method="post" target="ifrmEdit" action="/promotion/submit-edit">
                    <div class="form-body">
                        <div class="form-group">
                            <label class="col-md-3 control-label">Tiêu đề:</label>
                            <div class="col-md-6">
                                <?php echo $this->formText(
                                    'name',
                                    $this->dataInfo ? $this->dataInfo->{DbTable_Promotion::COL_PROMOTION_TITLE} : null,
                                    array('class' => 'validate[required] form-control')
                                ); ?>
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-md-3 control-label">Hình đại diện (270 x 200)<span class="required" aria-required="true"> * </span>:</label>
                            <div class="col-md-6">
                                <?php if ($this->dataInfo && $this->dataInfo->{DbTable_Promotion::COL_PROMOTION_IMAGE}) {
                                    echo $this->showImage($this->dataInfo->{DbTable_Promotion::COL_PROMOTION_IMAGE}, 150);
                                    echo '<br />';
                                } ?>
                                <input type="file" id="file_image" name="file_image" class="<?php echo $this->dataInfo ? '' : 'validate[required]';?>"/>
                                <?php echo $this->formHidden(
                                    'image',
                                    $this->dataInfo ? $this->dataInfo->{DbTable_Promotion::COL_PROMOTION_IMAGE} : null
                                ); ?>
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-md-3 control-label">Hình slider - chi tiết (1170 x 330)<span class="required" aria-required="true"> * </span>:</label>
                            <div class="col-md-6">
                                <?php if ($this->dataInfo && $this->dataInfo->{DbTable_Promotion::COL_PROMOTION_IMAGE_SLIDER}) {
                                    echo $this->showImage($this->dataInfo->{DbTable_Promotion::COL_PROMOTION_IMAGE_SLIDER}, 250);
                                    echo '<br />';
                                } ?>
                                <input type="file" id="file_imageSlider" name="file_imageSlider" class="<?php echo $this->dataInfo ? '' : 'validate[required]';?>"/>
                                <?php echo $this->formHidden(
                                    'imageSlider',
                                    $this->dataInfo ? $this->dataInfo->{DbTable_Promotion::COL_PROMOTION_IMAGE_SLIDER} : null
                                ); ?>
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-md-3 control-label">Ngày hết hạn:</label>
                            <div class="col-md-3">
                                <div class="input-group input-medium date date-picker" data-date-format="dd-mm-yyyy" data-date-start-date="+0d">

                                    <?php echo $this->formText(
                                        'expiredDate',
                                        $this->dataInfo ? $this->dataInfo->{DbTable_Promotion::COL_PROMOTION_EXPIRED_DATE} : null,
                                        array('class' => 'datepicker validate[required] form-control', 'readonly' =>'readonly')
                                    ); ?>
                                    <span class="input-group-btn">
                                    <button class="btn default" type="button"><i class="fa fa-calendar"></i></button>
                                    </span>
                                </div>

                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-md-3 control-label">Mô tả<span class="required" aria-required="true"> * </span>:</label>
                            <div class="col-md-9">
                                <?php echo $this->formTextarea(
                                    'subContent',
                                    $this->dataInfo ? $this->dataInfo->{DbTable_Promotion::COL_PROMOTION_SUB_CONTENT} : null,
                                    array('rows' => 3,'class' => 'validate[required]')
                                ); ?>
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-md-3 control-label">Nội dung<span class="required" aria-required="true"> * </span>:</label>
                            <div class="col-md-9">
                                <?php echo $this->formTextarea(
                                    'content',
                                    $this->dataInfo ? $this->dataInfo->{DbTable_Promotion::COL_PROMOTION_CONTENT} : null,
                                    array('rows' => 3, 'class' => 'validate[required]')
                                ); ?>
                            </div>
                        </div>



                        <div class="form-actions right">
                            <?php echo $this->formHidden(
                                'id',
                                $this->dataInfo ? $this->dataInfo->{DbTable_Promotion::COL_PROMOTION_ID} : null
                            ); ?>
                            <button type="submit" class="btn green">Cập nhật</button>
                        </div>
                </form>
            </div>
        </div>
        <!-- END SAMPLE FORM PORTLET-->
    </div>
    <iframe name="ifrmEdit" id="ifrmEdit" style="display: none"></iframe>
</div>