<!-- BEGIN PAGE HEADER-->
<div class="row">
    <div class="col-md-12">
        <!-- BEGIN PAGE TITLE & BREADCRUMB-->
        <h3 class="page-title">
            Quản lý khuyến mãi - Danh sách khuyến mãi
        </h3>
        <ul class="page-breadcrumb breadcrumb">
            <li>
                <i class="fa fa-home"></i>
                <a href="/">Home</a>
                <i class="fa fa-angle-right"></i>
            </li>
            <li>
                Danh sách khuyến mãi
            </li>
        </ul>
        <!-- END PAGE TITLE & BREADCRUMB-->
    </div>
</div>



<div class="row">
    <div class="col-md-12">
        <!-- BEGIN EXAMPLE TABLE PORTLET-->
        <div class="portlet box grey-cascade">
            <div class="portlet-title">
                <div class="caption">
                    <i class="fa fa-globe"></i><?php echo $this->pagination->getTotalItemCount(); ?> dòng(s)
                </div>
                <div class="actions">
                    <div class="item-actions">
                        <label>Cập nhật hàng loạt:</label>
                        <select id="manualUpdateElement">
                            <option value="">Chọn hành động...</option>
                            <option value="activate">Active</option>
                            <option value="inactivate">Inactive</option>>
                        </select>
                    </div>
                </div>

            </div>
            <div class="portlet-body">
                <div class="table-toolbar">
                    <div class="btn-group">
                        <button id="btn_add_new" class="btn green">
                            Thêm mới <i class="fa fa-plus"></i>
                        </button>
                    </div>
                    <div class="pull-right margin-bottom-15">
                        <form method="get" action="">
                            <fieldset class="filter">
                                <?php echo $this->formText('title', $this->title, array('size' => 70, 'placeholder' => 'Tiêu đề', 'class' =>'input-inline form-control')); ?>
                                <?php echo $this->formSelect(
                                    'active',
                                    $this->active,
                                    array('class' => 'input-inline form-control'),
                                    array('-1' => 'Trạng thái') +  array(
                                        1 => 'Activate',
                                        0 => 'Inactivate'
                                    )
                                ); ?>
                                <?php echo $this->formText(
                                    'expiredDate',
                                    $this->expiredDate,
                                    array('placeholder' => 'Ngày hết hạn','class' => 'input-inline form-control datepicker validate[required]')
                                ); ?>


                                <input type="submit" value="Tìm kiếm" class="btn blue" />

                            </fieldset>

                        </form>
                    </div>
                </div>
                <table class="table table-striped table-bordered table-hover" id="table_promotion">
                    <thead>
                    <tr>
                        <th class="table-checkbox">
                            <input type="checkbox" class="group-checkable" data-set="#table_promotion .checkboxes"/>
                        </th>
                        <th>Tiêu đề</th>
                        <th>Mô tả</th>
                        <th>Ngày hết hạn</th>
                        <th>Trạng thái</th>
                        <th>Ngày tạo</th>
                        <th width="90">&nbsp;</th>
                    </tr>
                    </thead>
                    <tbody>
                    <?php foreach ($this->pagination as $data) {?>
                        <tr>
                            <td>
                                <?php echo $this->formCheckbox(
                                    null,
                                    $data->{DbTable_Promotion::COL_PROMOTION_ID},
                                    array('class' => 'checkboxes')
                                ); ?>
                            </td>
                            <td>
                                <?php echo $data->{DbTable_Promotion::COL_PROMOTION_TITLE}; ?>
                            </td>
                            <td>
                                <?php echo $data->{DbTable_Promotion::COL_PROMOTION_SUB_CONTENT}; ?>
                            </td>
                            <td>
                                <?php echo $data->{DbTable_Promotion::COL_PROMOTION_EXPIRED_DATE}; ?>
                            </td>
                            <td>
                                <?php echo $this->activeLabel($data->{DbTable_Promotion::COL_PROMOTION_ACTIVE}); ?>
                            </td>
                            <td>
                                <?php echo $data->{DbTable_Promotion::COL_PROMOTION_CREATED_AT}; ?>
                            </td>

                            <td>
                                <a href="<?php echo '/promotion/edit/?i=' . $data->{DbTable_Promotion::COL_PROMOTION_ID}; ?>">Cập nhật</a><br>
                            </td>
                        </tr>
                    <?php } ?>
                    </tbody>
                    <tfoot>
                    <tr>
                        <td colspan="99">
                            <?php echo $this->pagination; ?>
                        </td>
                    </tr>
                    </tfoot>
                </table>

            </div>
        </div>
        <!-- END EXAMPLE TABLE PORTLET-->
    </div>
</div>