Xin chào <strong><?php echo $this->adminInfo->{DbTable_Admin::COL_ADMIN_FULLNAME};  ?></strong>.
<p>Theo như yêu cầu của bạn, chúng tôi đã tạo ra 1 mật khẩu mới theo thông tin dưới đây</p>
<table cellpadding="8" cellspacing="8" style="border:1px solid #ccc;">
    <tr>
        <td style="background: #ccc;">Mật khẩu mới:</td>
        <td><strong><?php echo $this->password; ?></strong></td>
    </tr>
    <tr>
        <td style="background: #ccc;">Truy cập hệ thống:</td>
        <td><a href="http://admin.pasoto.com">http://admin.pasoto.com</a></td>
    </tr>
</table>
<p>Email được gửi tự động, vui lòng không trả lời email này.</p>
<p>Xin cảm ơn và chúc bạn 1 ngày làm việc tốt lành.</p>
<p><em>(*)Gửi từ hệ thống Pasoto.com vào lúc <?php echo date('Y-m-d H:i:s'); ?></em></p>