Xin chào <strong><?php echo $this->customerName;  ?></strong>.
<p>Bài đăng của bạn phù hợp những quy định của Xome, chúng tôi đã duyệt tin của bạn. Bạn có thể xem trang chi tiêt theo link bên dưới.</p>
<table cellpadding="8" cellspacing="8" style="border:1px solid #ccc;">

    <tr>
        <td style="background: #ccc;">Truy cập trang chi tiết:</td>
        <td><a href="<?php echo $this->url?>"><?php echo $this->url?></a></td>
    </tr>
</table>
<p>Email được gửi tự động, vui lòng không trả lời email này.</p>
<p>Xin cảm ơn và chúc bạn 1 ngày làm việc tốt lành.</p>
<p><em>(*)Gửi từ hệ thống Xome - Phòng trọ sinh viên (Xomtro) vào lúc <?php echo date('Y-m-d H:i:s'); ?></em></p>