<div class="vertical-menu-content is-home">
    <ul class="vertical-menu-list">
        <li><a href="/thue-tro/sai-gon/quan-1"> <img class="icon-menu"  src="<?php echo HOST_STATIC_DEFAULT;?>data/list_bulleted.png">  Quận 1 </a></li>

        <li><a href="/thue-tro/sai-gon/quan-3"> <img class="icon-menu"  src="<?php echo HOST_STATIC_DEFAULT;?>data/list_bulleted.png">  Quận 3 </a></li>
        <li><a href="/thue-tro/sai-gon/quan-4"> <img class="icon-menu"  src="<?php echo HOST_STATIC_DEFAULT;?>data/list_bulleted.png">  Quận 4 </a></li>
        <li><a href="/thue-tro/sai-gon/quan-5"> <img class="icon-menu"  src="<?php echo HOST_STATIC_DEFAULT;?>data/list_bulleted.png">  Quận 5 </a></li>
        <li><a href="/thue-tro/sai-gon/quan-6"> <img class="icon-menu"  src="<?php echo HOST_STATIC_DEFAULT;?>data/list_bulleted.png">  Quận 6 </a></li>
        <li><a href="/thue-tro/sai-gon/quan-7"> <img class="icon-menu"  src="<?php echo HOST_STATIC_DEFAULT;?>data/list_bulleted.png">  Quận 7 </a></li>
        <li><a href="/thue-tro/sai-gon/quan-8"> <img class="icon-menu"  src="<?php echo HOST_STATIC_DEFAULT;?>data/list_bulleted.png">  Quận 8 </a></li>
        <li><a href="/thue-tro/sai-gon/quan-10"> <img class="icon-menu"  src="<?php echo HOST_STATIC_DEFAULT;?>data/list_bulleted.png">  Quận 10 </a></li>

        <li><a href="/nha-tro/sai-gon/quan-12"> <img class="icon-menu"  src="<?php echo HOST_STATIC_DEFAULT;?>data/list_bulleted.png">  Quận 12 </a></li>


    </ul>
    <div class="all-category"><a href="#"><span class="open-cate">Tất cả</span></a></div>
</div>