<div id="header" class="header" style="height: auto;min-height">
    <div class="top-header">
        <div class="container">
            <div class="nav-top-links">
                <a class="first-item" href="#">XOME | PHÒNG TRỌ SINH VIÊN </a>
                <a href="#" class="hidden-xs">Liên hệ: +01224678951</a>
            </div>

            <!-- <a class="btn-fb-login" href="#">Login fb</a>-->
            <div class="support-link hidden-xs">
                <?php if (!$this->customerInfo) { ?>
                    <a href="/tai-khoan/dang-ky.html">Đăng ký</a>
                    <a href="/tai-khoan/dang-nhap.html">Đăng nhập</a>
                <?php }else{?>

                    <a href="/tai-khoan/thong-tin.html"><i class="icon-user mr-sm mt-sm"></i><?php echo $this->customerInfo->{DbTable_Customer::COL_CUSTOMER_FIST_NAME} ?></a>
                <?php }?>
            </div>

        </div>
    </div>
    <!--/.top-header -->
    <!-- MAIN HEADER -->
    <div id="main-header">
        <div class="container main-header" style="padding: 0px 0px 6px 0px;">
            <div class="row">
                <div class="hidden-xs col-sm-2 logo">
                    <a href="/"><img alt="Xome - Nhà trọ sinh viên" src="<?php echo HOST_STATIC_DEFAULT;?>images/logo.png" style="height:130px;"/></a>
                </div>
                <div class="hidden-xs col-sm-10">
                    <a href="/"><img alt="Xome - Nhà trọ sinh viên" src="<?php echo HOST_STATIC_DEFAULT;?>images/banner.jpg" style="width:100%;"/></a>
                </div>

                <!--<div id="main-menu" class="col-sm-12 col-md-8 main-menu">
                    <nav class="navbar navbar-default">
                        <div class="container-fluid">
                            <div class="navbar-header">
                                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                                    <i class="fa fa-bars"></i>
                                </button>
                                <a class="navbar-brand" href="#">
				<a href="/">
				<img alt="Xhome - Nhà trọ sinh viên" src="<?php echo HOST_STATIC_DEFAULT;?>images/logo.png" style="height:130px;"/></a>

				</a>
                            </div>
                            <?php /*echo $this->render('widgets/menu.phtml'); */?>
                        </div>
                    </nav>
                </div>-->

            </div>
        </div>
    </div>
    <!-- END MANIN HEADER -->
    <div class="nav-top-menu" id="nav-top-menu">
        <div class="container">
            <div class="row">

                <div id="main-menu" class="col-sm-12 col-md-12 main-menu">
                    <nav class="navbar navbar-default">
                        <div class="container-fluid">
                            <div class="navbar-header">
                                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                                    <i class="fa fa-bars"></i>
                                </button>
                                <a class="navbar-brand" href="#"><a href="/">
                                        <img alt="Xome - Nhà trọ sinh viên" src="<?php echo HOST_STATIC_DEFAULT;?>images/logo.png" style="height:50px;"/></a>
                                </a>
                            </div>
                            <?php echo $this->render('widgets/menu.phtml'); ?>
                        </div>
                    </nav>
                </div>

            </div>
        </div>
    </div>
</div>
