<!-- block category -->
<!--<div class="block left-module">
    <p class="title_block">Tỉnh/Thành</p>
    <div class="block_content">
        <div class="layered layered-category">
            <div class="layered-content">
                <ul class="tree-menu">
                    <li class="active">
                        <span></span><a href="#">Hồ Chí Minh</a>
                        <ul>
                            <li><span></span><a href="#">Q.5</a></li>
                            <li><span></span><a href="#">Q.6</a></li>
                            <li><span></span><a href="#">Q.7</a></li>
                            <li><span></span><a href="#">Q.8</a></li>
                            <li><span></span><a href="#">Q.9</a></li>
                            <li><span></span><a href="#">Q.Tan Binh</a></li>
                            <li><span></span><a href="#"><span></span>Blouses</a></li>
                        </ul>
                    </li>
                    <li><span></span><a href="#">Hà Nội</a></li>
                    <li><span></span><a href="#">Cần Thơ</a></li>
                    <li><span></span><a href="#">Hải Phòng</a></li>
                    <li><span></span><a href="#">Đà Nẵng</a></li>
                    <li><span></span><a href="#">Đà Lạt</a></li>
                    <li><span></span><a href="#">Huế</a></li>
                    <li><span></span><a href="#">Nha Trang</a></li>
                    <li><span></span><a href="#">Mỹ Tho</a></li>
                </ul>
            </div>
        </div>

    </div>
</div>-->
<!-- ./block category  -->
<div class="block left-module">
    <form id="frmFilter" action="/tim-kiem" novalidate="novalidate">
    <p class="title_block">Filter selection
        <input class="btn btn-xs btn-primary pull-right" style="margin-right: 5px;" id="bnt-filter-update" type="submit" value="Cập nhật">
    </p>
    <div class="block_content">
        <!-- layered -->
        <div class="layered layered-filter-price">

            <!-- ./filter categgory -->
            <div class="layered_subtitle">DANH MỤC</div>
            <div class="layered-content filter-category">
                <ul class="check-box-list">
                    <li>
                        <input type="checkbox" id="categgory3" name="category" value="1" class="checkbox-radio">
                        <label for="categgory3">
                            <span class="button"></span>
                            NHÀ CHO THUÊ
                        </label>
                    </li>
                    <li>
                        <input type="checkbox" id="categgory2" name="category" value="2" class="checkbox-radio">
                        <label for="categgory2">
                            <span class="button"></span>
                            PHÒNG CHO THUÊ
                        </label>
                    </li>
                    <li>
                        <input type="checkbox" id="categgory1" name="category" value="3" class="checkbox-radio">
                        <label for="categgory1">
                            <span class="button"></span>
                            TÌM NGƯỜI Ở GHÉP
                        </label>
                    </li>

                </ul>
            </div>
            <!-- ./filter categgory -->

            <!-- filter district -->
            <div class="layered_subtitle">QUẬN/HUYỆN</div>
            <div class="layered-content">
                <ul class="check-box-list">

                    <li>
                        <input type="checkbox" id="c760" name="district" value="760">
                        <label for="c760">
                            <span class="button"></span>
                            Quận 1
                        </label>
                    </li>



                    <li>
                        <input type="checkbox" id="c769" name="district" value="769">
                        <label for="c769">
                            <span class="button"></span>
                            Quận 2
                        </label>
                    </li>
                    <li>
                        <input type="checkbox" id="c770" name="district" value="770">
                        <label for="c770">
                            <span class="button"></span>
                            Quận 3
                        </label>
                    </li>
                    <li>
                        <input type="checkbox" id="c773" name="district" value="773">
                        <label for="c773">
                            <span class="button"></span>
                            Quận 4
                        </label>
                    </li>
                    <li>
                        <input type="checkbox" id="c774" name="district" value="774">
                        <label for="c774">
                            <span class="button"></span>
                            Quận 5
                        </label>
                    </li>
                    <li>
                        <input type="checkbox" id="c775" name="district" value="775">
                        <label for="c775">
                            <span class="button"></span>
                            Quận 6
                        </label>
                    </li>
                    <li>
                        <input type="checkbox" id="c778" name="district" value="778">
                        <label for="c778">
                            <span class="button"></span>
                            Quận 7
                        </label>
                    </li>
                    <li>
                        <input type="checkbox" id="c776" name="district" value="776">
                        <label for="c776">
                            <span class="button"></span>
                            Quận 8
                        </label>
                    </li>

                    <li>
                        <input type="checkbox" id="c763" name="district" value="763">
                        <label for="c763">
                            <span class="button"></span>
                            Quận 9
                        </label>
                    </li>
                    <li>
                        <input type="checkbox" id="c771" name="district" value="771">
                        <label for="c771">
                            <span class="button"></span>
                            Quận 10
                        </label>
                    </li>
                    <li>
                        <input type="checkbox" id="c772" name="district" value="772">
                        <label for="c772">
                            <span class="button"></span>
                            Quận 11
                        </label>
                    </li>

                    <li>
                        <input type="checkbox" id="c761" name="district" value="761">
                        <label for="c761">
                            <span class="button"></span>
                            Quận 12
                        </label>
                    </li>
                    <li>
                        <input type="checkbox" id="c777" name="district" value="777">
                        <label for="c777">
                            <span class="button"></span>
                            Quận Bình Tân
                        </label>
                    </li>
                    <li>
                        <input type="checkbox" id="c762" name="district" value="762">
                        <label for="c762">
                            <span class="button"></span>
                            Quận Thủ Đức
                        </label>
                    </li>
                    <li>
                        <input type="checkbox" id="c764" name="district" value="764">
                        <label for="c764">
                            <span class="button"></span>
                            Quận Gò Vấp
                        </label>
                    </li>
                    <li>
                        <input type="checkbox" id="c765" name="district" value="765">
                        <label for="c765">
                            <span class="button"></span>
                            Quận Bình Thạnh
                        </label>
                    </li>
                    <li>
                        <input type="checkbox" id="c766" name="district" value="766">
                        <label for="c766">
                            <span class="button"></span>
                            Quận Tân Bình
                        </label>
                    </li>
                    <li>
                        <input type="checkbox" id="c767" name="district" value="767">
                        <label for="c767">
                            <span class="button"></span>
                            Quận Tân Phú
                        </label>
                    </li>
                    <li>
                        <input type="checkbox" id="c768" name="district" value="768">
                        <label for="c768">
                            <span class="button"></span>
                            Quận Phú Nhuận
                        </label>
                    </li>

                    <li>
                        <input type="checkbox" id="c783" name="district" value="783">
                        <label for="c783">
                            <span class="button"></span>
                            Huyện Củ Chi
                        </label>
                    </li>
                    <li>
                        <input type="checkbox" id="c784" name="district" value="784">
                        <label for="c784">
                            <span class="button"></span>
                            Huyện Hóc Môn
                        </label>
                    </li>
                    <li>
                        <input type="checkbox" id="c785" name="district" value="785">
                        <label for="c785">
                            <span class="button"></span>
                            Huyện Bình Chánh
                        </label>
                    </li>
                    <li>
                        <input type="checkbox" id="c786" name="district" value="786">
                        <label for="c786">
                            <span class="button"></span>
                            Huyện Nhà Bè
                        </label>
                    </li>
                    <li>
                        <input type="checkbox" id="c787" name="district" value="787">
                        <label for="c787">
                            <span class="button"></span>
                            Huyện Cần Giờ
                        </label>
                    </li>
                </ul>
                <!--
                <ul class="check-box-list">

                    <?php /*foreach ($this->districtData as $key => $districtName) {  */?>
                        <li>
                            <input type="checkbox" id="c<?php /*echo $key; */?>" name="cc">
                            <label for="c<?php /*echo $key; */?>">
                                <span class="button"></span>
                                Quận <?php /*echo $districtName; */?>
                                </span>
                            </label>
                        </li>
                    <?php /*} */?>
                </ul>-->
            </div>
            <!-- ./filter district -->
            <!-- filter price -->
            <div class="layered_subtitle">GIÁ THUÊ TRỌ</div>
            <div class="layered-content slider-range">

                <div data-label-reasult="Range:" data-min="0" data-max="30000000" data-unit="$" class="slider-range-price ui-slider ui-slider-horizontal ui-widget ui-widget-content ui-corner-all" data-value-min="0" data-value-max="30000000"></div>
                <div class="amount-range-price">Từ: 0 - 30.000.000</div>
                <ul class="check-box-list">
                    <li>
                        <input type="checkbox" id="p1" name="price-value" value="1" class="checkbox-radio">
                        <label for="p1">
                            <span class="button"></span>
                             < 1.000.0000
                        </label>
                    </li>
                    <li>
                        <input type="checkbox" id="p5" name="price-value" value="2" class="checkbox-radio">
                        <label for="p5">
                            <span class="button"></span>
                            1.000.0000 - 3.000.0000
                        </label>
                    </li>
                    <li>
                        <input type="checkbox" id="p2" name="price-value" value="3" class="checkbox-radio">
                        <label for="p2">
                            <span class="button"></span>
                            3.000.0000 - 5.000.0000
                        </label>
                    </li>
                    <li>
                        <input type="checkbox" id="p3" name="price-value" value="4" class="checkbox-radio">
                        <label for="p3">
                            <span class="button"></span>
                            5.000.0000 - 10.000.0000
                        </label>
                    </li>
                    <li>
                        <input type="checkbox" id="p4" name="price-value" value="5" class="checkbox-radio">
                        <label for="p4">
                            <span class="button"></span>
                            > 10.000.0000
                        </label>
                    </li>
                </ul>
            </div>
            <!-- ./filter price -->
            <!-- filter color -->

            <!-- ./filter color -->
            <!-- ./filter brand -->
            <div class="layered_subtitle">ĐỐI TƯỢNG THUÊ</div>
            <div class="layered-content filter-brand">
                <ul class="check-box-list">
                    <li>
                        <input type="checkbox" id="object3" name="object" value="1" class="checkbox-radio">
                        <label for="object3">
                            <span class="button"></span>
                            NAM
                        </label>
                    </li>
                    <li>
                        <input type="checkbox" id="object2" name="object" value="2" class="checkbox-radio">
                        <label for="object2">
                            <span class="button"></span>
                            NỮ
                        </label>
                    </li>

                </ul>
            </div>
            <!-- ./filter brand -->

           <!-- <div class="layered_subtitle">Tuyến đường</div>
            <div class="layered-content filter-brand">
                <ul class="check-box-list">
                    <li>
                        <input type="checkbox" id="street1" name="street" class="checkbox-radio">
                        <label for="street1">
                            <span class="button"></span>
                            Tấn Phát
                        </label>
                    </li>
                    <li>
                        <input type="checkbox" id="street2" name="street" class="checkbox-radio">
                        <label for="street2">
                            <span class="button"></span>
                            Nguyen Van Cu
                        </label>
                    </li>
                    <li>
                        <input type="checkbox" id="street3" name="street" class="checkbox-radio">
                        <label for="street3">
                            <span class="button"></span>
                            Ton Dan
                        </label>
                    </li>
                </ul>
            </div>-->
            <!-- ./filter size -->
            <div class="layered_subtitle">Tiện ích</div>
            <div class="layered-content filter-size">
                <ul class="check-box-list">
                    <li>
                        <input type="checkbox" id="size1" name="facility" value="4">
                        <label for="size1">
                            <span class="button"></span>Vệ sinh riêng
                        </label>
                    </li>
                    <li>
                        <input type="checkbox" id="size2" name="facility" value="3">
                        <label for="size2">
                            <span class="button"></span>Gác lửng
                        </label>
                    </li>
                    <li>
                        <input type="checkbox" id="size3" name="facility" value="2">
                        <label for="size3">
                            <span class="button"></span>Bãi đậu xe
                        </label>
                    </li>
                    <li>
                        <input type="checkbox" id="size4" name="facility" value="1">
                        <label for="size4">
                            <span class="button"></span>Wifi free
                        </label>
                    </li>
                    <li>
                        <input type="checkbox" id="size5" name="facility" value="5">
                        <label for="size5">
                            <span class="button"></span>Bao điện
                        </label>
                    </li>
                    <li>
                        <input type="checkbox" id="size9" name="facility" value="6">
                        <label for="size9">
                            <span class="button"></span>Bao nước
                        </label>
                    </li>
                    <li>
                        <input type="checkbox" id="size6" name="facility" value="7">
                        <label for="size6">
                            <span class="button"></span>Máy lạnh
                        </label>
                    </li>
                    <li>
                        <input type="checkbox" id="size7" name="facility" value="8">
                        <label for="size7">
                            <span class="button"></span>Máy giặt
                        </label>
                    </li>
                    <li style="width: 100%">
                        <input type="checkbox" id="size8" name="facility" value="9">
                        <label for="size8">
                            <span class="button"></span> Không chung chủ
                        </label>
                    </li>

                </ul>
            </div>
            <!-- ./filter size -->
        </div>
        <!-- ./layered -->

    </div>
    </form>
</div>