<div class="group-banner4">



    <div class="container">
        <div class="service ">
            <div class="col-xs-6 col-sm-3 service-item">
                <div class="icon">
                    <img alt="Tiện lợi" src="http://static.truyen.ln3.in/statics/asset/default/data/s1.png">
                </div>
                <div class="info">
                    <a href="#"><h3>Tiện lợi</h3></a>
                    <span>Đọc truyện một cách đơn giản, dễ dàng</span>
                </div>
            </div>
            <div class="col-xs-6 col-sm-3 service-item">
                <div class="icon">
                    <img alt="Thoải mái" src="http://static.truyen.ln3.in/statics/asset/default/data/s2.png">
                </div>
                <div class="info">
                    <a href="#"><h3>Thoải mái</h3></a>
                    <span>Sẽ không có quảng cáo làm phiền</span>
                </div>
            </div>
            <div class="col-xs-6 col-sm-3 service-item">
                <div class="icon">
                    <img alt="Hỗ trợ 24/7" src="http://static.truyen.ln3.in/statics/asset/default/data/s3.png">
                </div>

                <div class="info">
                    <a href="#"><h3>Hỗ trợ 24/7</h3></a>
                    <span>Giải đáp mọi thắc mắc</span>
                </div>
            </div>
            <div class="col-xs-6 col-sm-3 service-item">
                <div class="icon">
                    <img alt="Chất lượng" src="http://static.truyen.ln3.in/statics/asset/default/data/s4.png">
                </div>
                <div class="info">
                    <a href="#"><h3>Chất lượng</h3></a>
                    <span>Nội dung được dịch cẩn thận</span>
                </div>
            </div>
        </div>
    </div>

</div>