
<div id="page-content" class="page-content">
    <!-- Breadcrumb -->
    <div class="container">
        <ol class="breadcrumb">
            <li><a href="/">Trang chủ</a></li>
            <li class="active">Đăng tin thành công</li>
        </ol>
    </div>
    <!-- end Breadcrumb -->

    <div class="container">
        <div class="row">
           
            <!-- /.col-md-3 -->
            <!-- end Sidebar -->
            <!-- Property Detail Content -->
            <div class="col-md-9 col-sm-9">
                <div class="alert alert-success">
                    <strong><i class="fa fa-thumbs-o-up"></i> Thành công!</strong> Bạn đã đăng tin thành công.
                    Nhà trọ của bạn sẽ được chúng tôi kiểm duyệt và sẽ công khai trong thời gian sớm nhất.
                </div>

            </div><!-- /.col-md-9 -->
            <!-- end Property Detail Content -->
			 <!-- sidebar -->
            <div class="col-md-3 col-sm-3" id="left_column">

                <div class="block left-module">
                    <p class="title_block">Tin tức khác</p>

                    <div class="block_content">
                        <!-- layered -->
                        <div class="layered">
                            <div class="layered-content">
                                <ul class="blog-list-sidebar clearfix">
                                    <?php foreach ($this->productRelationData as $productRelation) {?>
                                        <li>
                                            <div class="post-thumb">
                                                <a href="/<?php echo $this->productCategoryIdentify($productRelation[DbTable_Product::COL_PRODUCT_CATEGORY_ID]) . '/ho-chi-minh/' . $this->districtIdentify($productRelation[DbTable_Product::COL_FK_DISTRICT]).'/' . $productRelation[DbTable_Product::COL_PRODUCT_IDENTIFY] . '-' .$this->productEncode($productRelation[DbTable_Product::COL_PRODUCT_ID]); ?>"><img src="<?php echo $this->showImageUrl($productRelation[DbTable_Product::COL_PRODUCT_THUMB_NAIL], $productRelation[DbTable_Product::COL_PRODUCT_REFER_LINK]!='', 90);?>" alt="xome" style="height: 50px;width: 100%;"></a>
                                            </div>
                                            <div class="post-info">
                                                <h5 class="entry_title"><a href="/<?php echo $this->productCategoryIdentify($productRelation[DbTable_Product::COL_PRODUCT_CATEGORY_ID]) . '/ho-chi-minh/' . $this->districtIdentify($productRelation[DbTable_Product::COL_FK_DISTRICT]).'/' . $productRelation[DbTable_Product::COL_PRODUCT_IDENTIFY] . '-' .$this->productEncode($productRelation[DbTable_Product::COL_PRODUCT_ID]); ?>"><?php echo $productRelation[DbTable_Product::COL_PRODUCT_NAME];?></a></h5>

                                                <div class="post-meta">
                                                    <span class="date"><i class="fa fa-calendar"></i> <?php echo $this->formatTime($productRelation[DbTable_Product::COL_PRODUCT_CREATED_AT]);?></span>
                                                    <!--<span class="comment-count">
                                                        <i class="fa fa-comment-o"></i> 3
                                                    </span>-->
                                                </div>
                                            </div>
                                        </li>
                                    <?php } ?>
                                </ul>
                            </div>
                        </div>
                        <!-- ./layered -->
                    </div>
                </div>
            </div>

        </div><!-- /.row -->
    </div><!-- /.container -->
</div>


