<section class="mt-lg  section-product" style="margin-top:10px;">
    <div class="container">

        <div class="row">
            <div class="col-md-12">

                <div class="row">
                    <div class="col-md-3">
                        <?php echo $this->render('widgets/sidebar-left.phtml'); ?>
                    </div>
                    <div class="col-md-9">
                        <h3 class="title-h3"> ĐƠN HÀNG</h3>

                        <div class="alert alert-success">
                            <strong><i class="fa fa-thumbs-o-up"></i> Thành công!</strong> Bạn đã đặt hàng thành công.
                            Chúng tôi sẽ liên lạc lại bạn trong thời gian sớm nhất.
                        </div>
                    </div>
                </div>

            </div>

        </div>
    </div>
</section>


