<!-- BEGIN PAGE HEADER-->
<div class="row">
    <div class="col-md-12">
        <!-- BEGIN PAGE TITLE & BREADCRUMB-->
        <h3 class="page-title">
            Quản lý bài viết - Thêm mới/Cập nhật
        </h3>
        <ul class="page-breadcrumb breadcrumb">
            <li>
                <i class="fa fa-home"></i>
                <a href="/">Home</a>
                <i class="fa fa-angle-right"></i>
            </li>
            <li>
                Thêm mới/Cập nhật
            </li>
        </ul>
        <!-- END PAGE TITLE & BREADCRUMB-->
    </div>
</div>


<div class="row">
    <div class="col-md-12 ">
        <!-- BEGIN SAMPLE FORM PORTLET-->
        <div class="portlet box blue ">
            <div class="portlet-title">
                <div class="caption">
                    <i class="fa fa-gift"></i> Thông tin bài viết
                </div>
            </div>
            <div class="portlet-body form">
                <form class="form-horizontal" role="form" id="validate" enctype="multipart/form-data" method="post" target="ifrmEdit" action="<?php echo $this->adminUrl('site-news/submit-edit'); ?>">
                    <div class="form-body">

                        <div class="form-group">
                            <label class="col-md-3 control-label">Tên:</label>
                            <div class="col-md-6">
                                <?php echo $this->formText(
                                    'name',
                                    $this->dataInfo ? $this->dataInfo->{DbTable_Blog::COL_BLOG_NAME} : null,
                                    array('class' =>'form-control')
                                ); ?>
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-md-3 control-label">Hình ảnh(300x400)<span class="required" aria-required="true"> * </span>:</label>
                            <div class="col-md-6">
                                <?php if ($this->dataInfo && $this->dataInfo->{DbTable_Blog::COL_BLOG_THUMB_IMAGE}) {

                                    echo !$this->dataInfo->{DbTable_Blog::COL_BLOG_IMPORT_FLAG} ? $this->showImage($this->dataInfo->{DbTable_Blog::COL_BLOG_THUMB_IMAGE}, 150) : '<img src="'.$this->dataInfo->{DbTable_Blog::COL_BLOG_THUMB_IMAGE}.'" width="150"/>';
                                    echo '<br />';
                                } ?>
                                <input type="file" id="file_image" name="file_image" class="margin-top-10"/>
                                <?php echo $this->formHidden(
                                    'image',
                                    $this->dataInfo ? $this->dataInfo->{DbTable_Blog::COL_BLOG_THUMB_IMAGE} : null
                                ); ?>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-md-3 control-label">Mô tả:</label>
                            <div class="col-md-6">
                                <?php echo $this->formTextarea(
                                    'description',
                                    $this->dataInfo ? $this->dataInfo->{DbTable_Blog::COL_BLOG_DESCRIPTION} : null,
                                    array('rows' => 3, 'class' => 'validate[maxSize[1024]]')
                                ); ?>
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-md-3 control-label">Nội dung:</label>
                            <div class="col-md-9">
                                <?php echo $this->formTextarea(
                                    'content',
                                    $this->dataInfo ? $this->dataInfo->{DbTable_Blog::COL_BLOG_CONTENT} : null,
                                    array('rows' => 3, 'class' => 'validate[required]')
                                ); ?>
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-md-3 control-label">Danh mục:</label>
                            <div class="col-md-6">
                                <?php echo $this->formSelect(
                                    'category',
                                    $this->dataInfo ? $this->dataInfo->{DbTable_Blog::COL_FK_BLOG_CATEGORY} : null,
                                    array('class' => 'validate[required]'),
                                    array('' => '++') + $this->categoryData
                                ); ?>
                            </div>
                        </div>

                        <div class="form-actions right">
                            <?php echo $this->formHidden(
                                'id',
                                $this->dataInfo ? $this->dataInfo->{DbTable_Blog::COL_BLOG_ID} : null
                            ); ?>
                            <button type="submit" class="btn green">Cập nhật</button>
                        </div>
                </form>
            </div>
        </div>
        <!-- END SAMPLE FORM PORTLET-->
    </div>
    <iframe name="ifrmEdit" id="ifrmEdit" style="display: none"></iframe>
</div>