<style>
    .panel-product-detail label{
        color:#ffffff;
    }
</style>
<div id="page-content" class="page-content">
    <!-- Breadcrumb -->
    <div class="container">
        <ol class="breadcrumb">
            <li><a href="/">Trang chủ</a></li>
            <li class="active">Đăng Tin</li>
        </ol>
    </div>
    <!-- end Breadcrumb -->

    <div class="container">
        <div class="row">
            <!-- Property Detail Content -->
            <div class="col-md-9 col-sm-9">
                <div class="panel-product-detail" style="border: 1px solid #ddd; padding: 20px; background: #999;">
                    <h2 class="page-heading mb-md">
                        <span class="page-heading-title">Đăng tin cho thuê</span>
                    </h2>
                    <form role="form" id="form-add" enctype="multipart/form-data" method="post" class="clearfix" action="/product/submit-add">
                        <div class="row">
                            <div class="col-md-12">
                                <div class="form-group">
                                    <label class="control-label" for="form-add-name">Tiêu đề<span class="required" aria-required="true"> 										* </span></label>
                                    <input type="text" class="form-control" id="form-add-name" name="name" placeholder="Nhà trọ Quận Bình Tân" required>
                                </div><!-- /.form-group -->
                            </div><!-- /.col-md-6 -->
                        </div><!-- /.row -->

                        <div class="row">
                            <div class="col-md-12">
                                <div class="form-group">
                                    <label class="control-label" for="form-add-categỏy">Danh mục<span class="required" aria-required="true"> 										* </span></label>
                                    <div class="radio-list">
                                        <label class="radio-inline">
                                            <input type="radio" name="categoryId" id="optionsRadios4"
                                                   value="1" checked> Nhà cho thuê </label>
                                        <label class="radio-inline">
                                            <input type="radio" name="categoryId" id="optionsRadios5"
                                                   value="2"> Phòng cho thuê </label>
                                        <label class="radio-inline">
                                            <input type="radio" name="categoryId" id="optionsRadios6"
                                                   value="3"> Tìm người ở ghép </label>
                                    </div>
                                </div><!-- /.form-group -->
                            </div><!-- /.col-md-6 -->
                        </div><!-- /.row -->

                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label class="control-label" for="form-add-name">Họ tên chủ nhà<span class="required" aria-required="true"> 										* </span></label>
                                    <input type="text" class="form-control" id="form-add-name" name="own" required value="<?php echo $this->customerInfo ? $this->customerInfo->{DbTable_Customer::COL_CUSTOMER_NAME} : '';?>">
                                </div><!-- /.form-group -->
                            </div><!-- /.col-md-6 -->
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label class="control-label" for="form-add-phone">Số điện thoại<span class="required" aria-required="true"> 										* </span></label>
                                    <input type="text" class="form-control" id="form-add-phone" name="phone" required value="<?php echo $this->customerInfo ? $this->customerInfo->{DbTable_Customer::COL_CUSTOMER_PHONE} : '';?>">
                                </div><!-- /.form-group -->
                            </div><!-- /.col-md-6 -->
                        </div><!-- /.row -->

                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label class="control-label" for="form-add-district">Quận/Huyện<span class="required" aria-required="true"> 										* </span></label>
                                    <select name="district" tabindex="-1" class="form-control" required>
                                        <option value="">Quận/Huyện</option>
                                        <option value="760"> Quận 1</option>
                                        <option value="769"> Quận 2</option>
                                        <option value="770"> Quận 3</option>
                                        <option value="773"> Quận 4</option>
                                        <option value="774"> Quận 5</option>
                                        <option value="775"> Quận 6</option>
                                        <option value="778"> Quận 7</option>
                                        <option value="776"> Quận 8</option>
                                        <option value="763"> Quận 9</option>
                                        <option value="771"> Quận 10</option>
                                        <option value="772"> Quận 11</option>
                                        <option value="761"> Quận 12</option>
                                        <option value="762"> Quận Thủ Đức</option>
                                        <option value="764"> Quận Gò Vấp</option>
                                        <option value="765"> Quận Bình Thạnh</option>
                                        <option value="766"> Quận Tân Bình</option>
                                        <option value="767"> Quận Tân Phú</option>
                                        <option value="768"> Quận Phú Nhuận</option>
                                        <option value="777"> Quận Bình Tân</option>
                                        <option value="783"> Quận Củ Chi</option>
                                        <option value="784"> Quận Hóc Môn</option>
                                        <option value="785"> Quận Bình Chánh</option>
                                        <option value="786"> Quận Nhà Bè</option>
                                        <option value="787"> Quận Cần Giờ</option>
                                    </select>
                                </div><!-- /.form-group -->
                            </div><!-- /.col-md-6 -->
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label class="control-label" for="form-add-object">Đối tượng thuê</label>
                                    <select class="form-control" name="object">
                                        <option value="">Không bắt buộc</option>
                                        <option value="1">Yêu cầu Nam</option>
                                        <option value="2">Yêu cầu Nữ</option>
                                    </select>
                                </div><!-- /.form-group -->
                            </div><!-- /.col-md-6 -->
                        </div><!-- /.row -->

                        <div class="row">
                            <div class="col-md-12">
                                <div class="form-group">
                                    <label class="control-label" for="form-add-address">Địa chỉ<span class="required" aria-required="true"> 										* </span></label>
                                    <input type="text" class="form-control" id="form-add-address" name="address" required>
                                </div><!-- /.form-group -->
                            </div><!-- /.col-md-6 -->
                        </div><!-- /.row -->
                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label class="control-label" for="form-add-price">Giá thuê<span class="required" aria-required="true"> 										* </span></label>
                                    <input type="number" class="form-control" id="form-add-price" name="paid_price" required>
                                </div><!-- /.form-group -->
                            </div><!-- /.col-md-6 -->
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label class="control-label" for="form-add-area">Diện tích<span class="required" aria-required="true"> 										* </span></label>
                                    <input type="number" class="form-control" id="form-add-area" name="area" required>
                                </div><!-- /.form-group -->
                            </div><!-- /.col-md-6 -->
                        </div><!-- /.row -->

                        <div class="row">
                            <div class="col-md-12">
                                <div class="form-group">
                                    <label class="control-label" for="form-add-file">Hình ảnh nhà trọ<span class="required" aria-required="true"> 										* </span></label>
                                    <input type="file" class="form-control" id="form-add-file" name="file_image[]" required multiple accept="image/*">
                                </div><!-- /.form-group -->
                            </div><!-- /.col-md-12 -->
                        </div><!-- /.row -->

                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label class="control-label" for="form-add-facility">Tiện ích</label>
                                    <div class="checkbox-list">
                                        <label>
                                            <input type="checkbox" name="facility[]" value="1"> Miễn phí wifi </label>
                                        <label>
                                            <input type="checkbox" name="facility[]" value="2"> Bãi đậu xe </label>
                                        <label>
                                            <input type="checkbox" name="facility[]" value="3"> Có gác/ lầu </label>
                                        <label>
                                            <input type="checkbox" name="facility[]" value="4"> Nhà vệ sinh riêng </label>

                                    </div>
                                </div><!-- /.form-group -->
                            </div><!-- /.col-md-6 -->
                            <div class="col-md-6">
                                <div class="form-group">

                                    <div class="checkbox-list">
                                        <label>
                                            <input type="checkbox" name="facility[]" value="5"> Bao điện </label>
                                        <label>
                                            <input type="checkbox" name="facility[]" value="6"> Bao nước </label>
                                        <label>
                                            <input type="checkbox" name="facility[]" value="7"> Máy lạnh </label>
                                        <label>
                                            <input type="checkbox" name="facility[]" value="8"> Máy giặt </label>
                                        <label>
                                            <input type="checkbox" name="facility[]" value="9"> Không chung chủ</label>

                                    </div>
                                </div><!-- /.form-group -->
                            </div><!-- /.col-md-6 -->
                        </div><!-- /.row -->


                        <div class="row">
                            <div class="col-md-12">
                                <div class="form-group">
                                    <label for="form-add-description">Thông tin chi tiết nhà trọ</label>
                                    <textarea class="form-control" id="form-add-description" rows="16" name="description">Tôi có 1 phòng trọ 123 Hồng Bàng, quận 6, cần cho thuê.</textarea>
                                </div><!-- /.form-group -->
                            </div><!-- /.col-md-12 -->
                        </div><!-- /.row -->



                        <div class="form-group clearfix">

                            <button type="submit" class="btn pull-right btn-default blue">Xác nhận</button>
                        </div><!-- /.form-group -->
                        <div id="form-status"></div>
                    </form><!-- /#form-add -->

                </div>

            </div><!-- /.col-md-9 -->
            <!-- end Property Detail Content -->

            <!-- sidebar -->
            <div class="col-md-3 col-sm-3" id="left_column">

                <div class="block left-module">
                    <p class="title_block">Tin tức khác</p>

                    <div class="block_content">
                        <!-- layered -->
                        <div class="layered">
                            <div class="layered-content">
                                <ul class="blog-list-sidebar clearfix">
                                    <?php foreach ($this->productRelationData as $productRelation) {?>
                                        <li>
                                            <div class="post-thumb">
                                                <a href="/<?php echo $this->productCategoryIdentify($productRelation[DbTable_Product::COL_PRODUCT_CATEGORY_ID]) . '/ho-chi-minh/' . $this->districtIdentify($productRelation[DbTable_Product::COL_FK_DISTRICT]).'/' . $productRelation[DbTable_Product::COL_PRODUCT_IDENTIFY] . '-' .$this->productEncode($productRelation[DbTable_Product::COL_PRODUCT_ID]); ?>"><img src="<?php echo $this->showImageUrl($productRelation[DbTable_Product::COL_PRODUCT_THUMB_NAIL], !$productRelation[DbTable_Product::COL_PRODUCT_FLAG_UPLOAD_IMAGE], 90);?>" alt="<?php echo $productRelation[DbTable_Product::COL_PRODUCT_NAME];?>" style="height: 100px;width: 100%;"></a>
                                            </div>
                                            <div class="post-info">
                                                <h5 class="entry_title"><a href="/<?php echo $this->productCategoryIdentify($productRelation[DbTable_Product::COL_PRODUCT_CATEGORY_ID]) . '/ho-chi-minh/' . $this->districtIdentify($productRelation[DbTable_Product::COL_FK_DISTRICT]).'/' . $productRelation[DbTable_Product::COL_PRODUCT_IDENTIFY] . '-' .$this->productEncode($productRelation[DbTable_Product::COL_PRODUCT_ID]); ?>"><?php echo $productRelation[DbTable_Product::COL_PRODUCT_NAME];?></a></h5>

                                                <div class="post-meta">
                                                    <span class="date"><i class="fa fa-calendar"></i> <?php echo $this->formatTime($productRelation[DbTable_Product::COL_PRODUCT_CREATED_AT]);?></span>
                                                    <!--<span class="comment-count">
                                                        <i class="fa fa-comment-o"></i> 3
                                                    </span>-->
                                                </div>
                                            </div>
                                        </li>
                                    <?php } ?>
                                </ul>
                            </div>
                        </div>
                        <!-- ./layered -->
                    </div>
                </div>
            </div>
            <!-- end Sidebar -->
        </div><!-- /.row -->
    </div><!-- /.container -->
</div>
