<aside id="advertising" class="block page-content">
    <div class="container">
        <a href="#form-contact" class="fancybox">
            <div class="banner">
                <div class="wrapper">
                    <span class="title">Nếu không tìm được nhà trọ phù hợp, bạn vui lòng để lại thông tin để bộ phận chăm sóc khách hàng hỗ trợ bạn tìm phòng ?</span>
                    <span class="submit">Gửi thông tin! <i class="fa fa-plus-square"></i></span>
                </div>
            </div><!-- /.banner-->
        </a>
    </div>
</aside>
<div class="container">
    <div class="col-md-9">
        <div class="gap-small"></div>

        <h3 class="title-h3" style="margin-top: 14px;">NHÀ TRỌ</h3>
        <?php echo $this->render('widgets/register-real-estate.phtml'); ?>
        <?php echo $this->render('widgets/product-list.phtml'); ?>
    </div>
    <div class="col-md-3 hidden-xs">
        <div class="gap-small"></div>
        <?php echo $this->render('widgets/sidebar-right.phtml'); ?>
    </div>
</div>
