<div class="slider-container light rev_slider_wrapper">
    <div id="revolutionSlider" class="slider rev_slider" data-plugin-revolution-slider data-plugin-options='{"gridwidth": 500, "gridheight": 500}'>
        <ul>
            <li data-transition="fade">
                <img src="<?php echo HOST_STATIC_DEFAULT;?>img/slides/light-cover.jpg"
                     alt=""
                     data-bgposition="center center"
                     data-bgfit="cover"
                     data-bgrepeat="no-repeat"
                     class="rev-slidebg">

                <div class="rs-background-video-layer"
                     data-forcerewind="on"
                     data-volume="mute"
                     data-videowidth="100%"
                     data-videoheight="100%"
                     data-videomp4="<?php echo HOST_STATIC_DEFAULT;?>video/light.mp4"
                     data-videopreload="preload"
                     data-videoloop="loop"
                     data-forceCover="1"
                     data-aspectratio="16:9"
                     data-autoplay="true"
                     data-autoplayonlyfirsttime="false"
                     data-nextslideatend="true"
                    ></div>

                <div class="tp-caption"
                     data-x="center" data-hoffset="-150"
                     data-y="188"
                     data-start="1000"
                     style="z-index: 5"
                     data-transform_in="x:[-300%];opacity:0;s:500;"><img src="<?php echo HOST_STATIC_DEFAULT;?>img/slides/slide-title-border-light.png" alt=""></div>

                <div class="tp-caption top-label"
                     data-x="center" data-hoffset="0"
                     data-y="188"
                     data-start="500"
                     style="z-index: 5"
                     data-transform_in="y:[-300%];opacity:0;s:500;">BẠN CẦN CHUYỂN </div>

                <div class="tp-caption"
                     data-x="center" data-hoffset="150"
                     data-y="188"
                     data-start="1000"
                     style="z-index: 5"
                     data-transform_in="x:[300%];opacity:0;s:500;"><img src="<?php echo HOST_STATIC_DEFAULT;?>img/slides/slide-title-border-light.png" alt=""></div>

                <div class="tp-caption main-label"
                     data-x="center" data-hoffset="0"
                     data-y="218"
                     data-start="1500"
                     data-whitespace="nowrap"
                     data-transform_in="y:[100%];s:500;"
                     data-transform_out="opacity:0;s:500;"
                     style="z-index: 5;font-size: 45px;"
                     data-mask_in="x:0px;y:0px;">CHỖ TRỌ MỚI?</div>

                <div class="tp-caption bottom-label"
                     data-x="center" data-hoffset="0"
                     data-y="288"
                     data-start="2000"
                     style="z-index: 5"
                     data-transform_in="y:[100%];opacity:0;s:500;">Xome hỗ trợ bạn tìm kiếm, tư vấn phòng trọ phù hợp giá cả sinh viên.</div>

            </li>
        </ul>
    </div>
</div>