<!DOCTYPE html>
<html>
<head>

    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="author" content="nguyennhan09cntt">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="keywords" content="<?php echo $this->metaKeyword;?>">
    <meta name="description" content="<?php echo $this->metaDescription;?>">
    <?php if (isset($this->canonical) && $this->canonical) { ?>
        <link rel="canonical" href="<?php echo $this->canonical;?>" />
    <? } ?>
    <meta property="og:locale" content="vi_VN">
    <meta property="og:type" content="website">
    <meta property="og:title" content="<?php if ($this->metaTitle) echo $this->metaTitle; ?>">
    <meta property="og:description" content="<?php echo $this->metaDescription;?>">
    <meta property="og:url" content="<?php echo Application_Function_Common::fullCurrentUrlNoParam();?>">
    <meta property="og:site_name" content="xome">
    <meta property="article:publisher" content="https://www.facebook.com/Xome-Pho%CC%80ng-Tro%CC%A3-Sinh-Vi%C3%AAn-1212428578819117/">
    <!-- <meta property="fb:admins" content="1471827889803836">-->
    <meta name="geo.region" content="VN" />
    <meta name="geo.position" content="14.058324;108.277199" />
    <meta name="ICBM" content="14.058324, 108.277199" />
    <title><?php if ($this->metaTitle) echo $this->metaTitle ; ?></title>

    <!-- Favicon -->
    <link rel="shortcut icon" href="/favicon.ico" type="image/x-icon" />
  <!--  <link rel="apple-touch-icon" href="<?php /*echo HOST_STATIC_DEFAULT;*/?>img/apple-touch-icon.png">-->

    <!-- Mobile Metas -->
    <meta name="viewport" content="width=device-width, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no">

    <!-- Web Fonts  -->
    <link href="http://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700,800%7CShadows+Into+Light" rel="stylesheet" type="text/css">

    <!-- Vendor CSS -->
    <link rel="stylesheet" href="<?php echo HOST_STATIC_DEFAULT;?>vendor/bootstrap/css/bootstrap.css">
    <link rel="stylesheet" href="<?php echo HOST_STATIC_DEFAULT;?>vendor/font-awesome/css/font-awesome.css">
    <link rel="stylesheet" href="<?php echo HOST_STATIC_DEFAULT;?>vendor/simple-line-icons/css/simple-line-icons.css">

    <link rel="stylesheet" href="<?php echo HOST_STATIC_DEFAULT;?>vendor/magnific-popup/magnific-popup.css">
    <link rel="stylesheet" type="text/css" href="<?php echo HOST_STATIC_DEFAULT;?>vendor/select2/css/select2.min.css" />
    <link rel="stylesheet" type="text/css" href="<?php echo HOST_STATIC_DEFAULT;?>vendor/jquery.bxslider/jquery.bxslider.css" />
    <link rel="stylesheet" type="text/css" href="<?php echo HOST_STATIC_GLOBAL;?>plugins/owl.carousel/owl.carousel.css" />
    <link rel="stylesheet" type="text/css" href="<?php echo HOST_STATIC_DEFAULT;?>vendor/jquery-ui/jquery-ui.css" />
    <link rel="stylesheet" type="text/css" href="<?php echo HOST_STATIC_DEFAULT;?>vendor/fancyBox/jquery.fancybox.css" />
    <link rel="stylesheet" type="text/css" href="<?php echo HOST_STATIC_GLOBAL;?>plugins/uniform/css/uniform.default.css" />


    <!-- Theme CSS -->
    <link rel="stylesheet" type="text/css" href="<?php echo HOST_STATIC_DEFAULT;?>css/animate.css" />






    <!-- Theme Custom CSS -->
    <link rel="stylesheet" type="text/css" href="<?php echo HOST_STATIC_DEFAULT;?>css/reset.css" />
    <link rel="stylesheet" type="text/css" href="<?php echo HOST_STATIC_DEFAULT;?>css/style.css" />
    <link rel="stylesheet" type="text/css" href="<?php echo HOST_STATIC_DEFAULT;?>css/responsive.css" />

    <!-- Skin CSS -->


    <!-- Current Page CSS -->
    <link rel="stylesheet" type="text/css" href="<?php echo HOST_STATIC_DEFAULT;?>css/timeline.css">

    <link rel="stylesheet" type="text/css" href="<?php echo HOST_STATIC_DEFAULT;?>css/custom.css" />
    <link rel="stylesheet" type="text/css" href="<?php echo HOST_STATIC_MOBILE;?>css/custom.css" />

    <!-- Head Libs -->
    <script src="<?php echo HOST_STATIC_DEFAULT;?>vendor/modernizr/modernizr.js"></script>
    <?php echo $this->headLink(); ?>

</head>
<body class="<?php echo $this->controllerName =='index' && $this->actionName == 'index' ? 'home' : ''?>">
<!-- HEADER -->
<?php echo $this->render('widgets/header.phtml'); ?>
<!-- end header -->
<?php echo $this->layout()->content; ?>
<?php echo $this->render('widgets/footer.phtml'); ?>

<a href="#" class="scroll_top" title="Scroll to Top" style="display: inline;">Scroll</a>
<div id="fb-root"></div>

<!-- Vendor -->
<script src="<?php echo HOST_STATIC_DEFAULT;?>vendor/jquery/jquery.js"></script>
<script src="<?php echo HOST_STATIC_DEFAULT;?>js/jquery-migrate-1.2.1.min.js"></script>

<script src="<?php echo HOST_STATIC_DEFAULT;?>vendor/jquery.appear/jquery.appear.js"></script>
<script src="<?php echo HOST_STATIC_DEFAULT;?>vendor/jquery.easing/jquery.easing.js"></script>
<script src="<?php echo HOST_STATIC_DEFAULT;?>vendor/jquery-cookie/jquery-cookie.js"></script>
<script src="<?php echo HOST_STATIC_DEFAULT;?>vendor/bootstrap/js/bootstrap.js"></script>
<script src="<?php echo HOST_STATIC_DEFAULT;?>vendor/common/common.js"></script>
<script src="<?php echo HOST_STATIC_DEFAULT;?>vendor/jquery.validation/jquery.validation.js"></script>
<script src="<?php echo HOST_STATIC_DEFAULT;?>vendor/jquery.validation/localization/messages_vi.js"></script>
<script src="<?php echo HOST_STATIC_DEFAULT;?>vendor/jquery.stellar/jquery.stellar.js"></script>
<script src="<?php echo HOST_STATIC_DEFAULT;?>vendor/jquery.easy-pie-chart/jquery.easy-pie-chart.js"></script>
<script src="<?php echo HOST_STATIC_DEFAULT;?>vendor/jquery.gmap/jquery.gmap.js"></script>
<script src="<?php echo HOST_STATIC_DEFAULT;?>vendor/jquery.lazyload/jquery.lazyload.js"></script>
<script src="<?php echo HOST_STATIC_DEFAULT;?>vendor/isotope/jquery.isotope.js"></script>
<script src="<?php echo HOST_STATIC_DEFAULT;?>vendor/magnific-popup/jquery.magnific-popup.js"></script>
<script src="<?php echo HOST_STATIC_DEFAULT;?>vendor/vide/vide.js"></script>
<script type="text/javascript" src="<?php echo HOST_STATIC_DEFAULT;?>vendor/select2/js/select2.min.js"></script>
<script type="text/javascript" src="<?php echo HOST_STATIC_DEFAULT;?>vendor/jquery.bxslider/jquery.bxslider.min.js"></script>
<script type="text/javascript" src="<?php echo HOST_STATIC_GLOBAL;?>plugins/owl.carousel/owl.carousel.min.js"></script>
<!--<script type="text/javascript" src="<?php /*echo HOST_STATIC_DEFAULT;*/?>vendor/countdown/jquery.plugin.js"></script>-->
<script type="text/javascript" src="<?php echo HOST_STATIC_DEFAULT;?>vendor/jquery.countdown/jquery.countdown.min.js"></script>
<!-- ./COUNTDOWN -->

<script type="text/javascript" src="<?php echo HOST_STATIC_DEFAULT;?>vendor/jquery-ui/jquery-ui.min.js"></script>

<script type="text/javascript" src="<?php echo HOST_STATIC_DEFAULT;?>vendor/jquery.elevatezoom.js"></script>
<script type="text/javascript" src="<?php echo HOST_STATIC_DEFAULT;?>vendor/fancyBox/jquery.fancybox.js"></script>
<!--<script type="text/javascript" src="<?php /*echo HOST_STATIC_DEFAULT;*/?>js/jquery.number.js"></script>-->
<script type="text/javascript" src="<?php echo HOST_STATIC_GLOBAL;?>plugins/uniform/jquery.uniform.min.js"></script>

<!-- Theme Base, Components and Settings -->
<script src="<?php echo HOST_STATIC_DEFAULT;?>js/theme.js"></script>
<script type="text/javascript" src="<?php echo HOST_STATIC_DEFAULT;?>js/theme-script.js"></script>
<script type="text/javascript" src="<?php echo HOST_STATIC_DEFAULT;?>js/jquery.actual.min.js"></script>
<script src="<?php echo HOST_STATIC_GLOBAL;?>plugins/ckeditor/ckeditor.js" type="text/javascript"></script>
<!-- Current Page Vendor and Views -->

<script type="text/javascript" src="http://maps.googleapis.com/maps/api/js?v=3&amp;sensor=true&key=AIzaSyB-AOx4WsiNTjZ3fne0YV8Jy6ngfwIH_f4&libraries=places,drawing"></script>

<!-- Theme Custom -->
<script src="<?php echo HOST_STATIC_DEFAULT;?>js/custom.js"></script>

<!-- Theme Initialization Files -->
<script src="<?php echo HOST_STATIC_DEFAULT;?>js/theme.init.js"></script>
<script src="<?php echo HOST_STATIC_DEFAULT;?>js/facebook.init.js"></script>

<!-- Current Page Vendor and Views -->
<script>
    jQuery(document).ready(function() {
        // initiate layout and plugins
        //Metronic.init(); // init metronic core components
    });
</script>
<?php echo $this->headScript(); ?>
<script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

    ga('create', 'UA-55709783-6', 'auto');
    ga('send', 'pageview');
</script>

</body>
</html>

