<div id="navbar" class="navbar-collapse collapse"style="margin-left: 15px;">
    <ul class="nav navbar-nav">
        <li class=""><a href="/">TRANG CHỦ</a></li>
        <li class=""><a href="/tim-kiem?<?php echo $this->queryPagination;?>">HIỂN THỊ THEO DANH SÁCH</a></li>
        <li style=""><a href="/dang-tin-cho-thue.html">ĐĂNG TIN CHO THUÊ</a></li>
		<li style=""><a href="/dang-tin-tim-phong.html">ĐĂNG TIN TÌM PHÒNG</a></li>
        <!--<li class="pull-right"><a href="category.html" class="btn">ĐĂNG TIN</a></li>-->
    </ul>
</div><!--/.nav-collapse -->