<footer class="" id="footer">
    <div class="container">
        <div class="row">
            <div class="footer-ribbon">
                <span>Thông tin</span>
            </div>
            <div class="col-md-3">
                <div class="newsletter">
                    <h4>Thông tin</h4>
                    <p>Xome là hệ thống cập nhật liên tục và nhanh nhất các tin tức phòng trọ do các thành viên đóng góp, có nhiều phòng trọ tiện nghi và nổi bật</p>
                </div>
            </div>
            <div class="col-md-3">
                <h4>Người sáng lập</h4>
                <div class="newsletter">
                    <ul>
                        <li><a href="http://nguyennhan09cntt.ln3.in" target="_blank">Thông tin</a></li>
                        <li><a href="http://nguyennhan09cntt.ln3.in/lien-he.html" target="_blank">Liên hệ</a></li>
                    </ul>
                </div>
            </div>
            <div class="col-md-3">
                <h4>Fanpage</h4>
                <iframe src="http://www.facebook.com/plugins/likebox.php?href=https://www.facebook.com/xome.vn/&amp;height=239&amp;width=262&amp;show_faces=true&amp;header=true&amp;action=like&amp;colorscheme=dark" scrolling="no" frameborder="0" style="border: none; width: 100%; height: 259px;" allowtransparency="false"></iframe>
            </div>
            <div class="col-md-3">
                <div class="contact-details">
                    <h4>Liên hệ</h4>
                    <ul class="contact">
                        <li><p><i class="fa fa-map-marker"></i> <strong>Địa chỉ:</strong> Đường 1A, Bình Tân, Hồ Chí Minh.</p></li>
                        <li><p><i class="fa fa-phone"></i> <strong>Phone:</strong>01633193495</p></li>
                        <li><p><i class="fa fa-envelope"></i> <strong>Email:</strong> <a href="mailto:nguyennhan09cntt@gmail.com">nguyennhan09cntt@gmail.com</a></p></li>
                    </ul>
                </div>
            </div>

        </div>
    </div>
    <div class="footer-copyright">
        <div class="container">
            <div class="row">
                <!--<div class="col-md-1">
                        <a href="/" class="logo">
                            <img alt="Ln3 Website" class="img-responsive" src="<?php /*echo HOST_STATIC_DEFAULT;*/?>img/logo-footer.png">
                        </a>
                    </div>-->
                <div class="col-md-8">
                    <p>© Copyright © 2016 Website chính thức LN3. Người sáng lập <a href="http://nguyennhan09cntt.ln3.in" target="_blank">Nguyễn Văn Trọng Nhân (Nguyễn Nhân)</a></p>
                </div>
                <div class="col-md-4">
                    <nav id="sub-menu">
                        <ul>
                            <!--  <li><a href="/cau-hoi-thuong-gap.html">FAQ's</a></li>
                              <li><a href="/sitemap.html">Sitemap</a></li>
                              <li><a href="/lien-he.html">Liên hệ</a></li>-->
                            <li><a href="/">Trang chủ</a></li>
                            <li><a href="/gioi-thieu.html">Giới thiệu</a></li>
                            <li><a href="/tin-tuc/tuyen-sinh.html">Tin tức</a></li>
                        </ul>
                    </nav>
                </div>
            </div>
        </div>
    </div>
</footer>
    