<footer id="footer2" class="pt-none">

    <!-- footer paralax-->
    <div class="footer-paralax">

        <div class="footer-row">
            <div class="container">
                <div class="row">
                    <div class="col-sm-3">
                        <div class="widget-container">
                            <h3 class="widget-title">THÔNG TIN</h3>
                            <div class="widget-body">
                                Xome là hệ thống cập nhật liên tục và nhanh nhất các tin tức phòng trọ do các thành viên đóng góp, có nhiều phòng trọ tiện nghi và nổi bật
                            </div>
                        </div>
                    </div>
                    <div class="col-sm-3">
                        <div class="widget-container">
                            <h3 class="widget-title">NGUÒI SÁNG LẬP</h3>
                            <div class="widget-body">
                                <ul>
                                    <li><a href="http://nguyennhan09cntt.ln3.in" target="_blank">Thông tin</a></li>
                                    <li><a href="http://nguyennhan09cntt.ln3.in/lien-he.html" target="_blank">Liên hệ</a></li>
                                </ul>
                            </div>
                        </div>
                    </div>
                    <div class="col-sm-3">
                        <div class="widget-container">
                            <h3 class="widget-title">Fan Page</h3>
                            <div class="widget-body">
                                <div class="fb-page" data-href="https://www.facebook.com/XHome-Pho&#x300;ng-Tro&#x323;-1212428578819117" data-small-header="true" data-adapt-container-width="true" data-hide-cover="true" data-show-facepile="false"><blockquote cite="https://www.facebook.com/XHome-Pho&#x300;ng-Tro&#x323;-1212428578819117" class="fb-xfbml-parse-ignore"><a href="https://www.facebook.com/XHome-Pho&#x300;ng-Tro&#x323;-1212428578819117">XHome - Phòng Trọ</a></blockquote></div>

                            </div>
                        </div>
                    </div>
                    <div class="col-sm-3">
                        <div class="widget-container">
                            <h3 class="widget-title">LIÊN HỆ</h3>
                            <div class="widget-body">
                                <ul>
                                    <li><a class="location" href="#">1A, Bình Tân, Hồ Chí Minh</a></li>
                                    <li><a class="phone" href="#">01224 6789 51</a></li>
                                    <li><a class="email" href="#">nguyennhan09cntt@gmail.com</a></li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="footer-bottom">
            <div class="container">
                <div class="footer-bottom-wapper">
                    <div class="row">
                        <div class="col-sm-12">
                            <div class="footer-coppyright">
                                Copyrights &#169; 2016 LN3. All Rights Reserved. Thiết kế by <a href="http://nguyennhan09cntt.ln3.in" target="_blank">Nguyễn Văn Trọng Nhân</a>
                            </div>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- ./footer paralax-->

</footer>

