<div class="panel-group panel-group-primary mt-md" id="category-province">
    <div class="panel panel-default">
        <div class="panel-heading" style="background-color: #0088cc; color: white;">
            <h4 class="panel-title">
                <a class="accordion-toggle" data-toggle="collapse" data-parent="#category-province"
                   href="#category-tieng-anh-data">
                    <i class="fa fa-bars"></i>
                    Thuê trọ Sài Gòn </a>
            </h4>
        </div>
        <div id="category-data" class="accordion-body collapse in">
            <div class="panel-body">
                <ul class="list list-icons list-quaternary">
                    <li class="appear-animation fadeInUp appear-animation-visible" data-appear-animation="fadeInUp"
                        data-appear-animation-delay="900" style="animation-delay: 900ms;"><i class="fa fa-check "></i><a href="/thue-tro/sai-gon/quan-1" > Thuê trọ Quận 1   </a></li>
                    <li class="appear-animation fadeInUp appear-animation-visible" data-appear-animation="fadeInUp"
                        data-appear-animation-delay="900" style="animation-delay: 900ms;"><i class="fa fa-check "></i><a href="/thue-tro/sai-gon/quan-12" > Thuê trọ Quận 12  </a></li>
                    <li class="appear-animation fadeInUp appear-animation-visible" data-appear-animation="fadeInUp"
                        data-appear-animation-delay="900" style="animation-delay: 900ms;"><i class="fa fa-check "></i><a href="/thue-tro/sai-gon/quan-thu-duc" > Thuê trọ Quận Thủ Đức  </a></li>
                    <li class="appear-animation fadeInUp appear-animation-visible" data-appear-animation="fadeInUp"
                        data-appear-animation-delay="900" style="animation-delay: 900ms;"><i class="fa fa-check "></i><a href="/thue-tro/sai-gon/quan-9" > Thuê trọ Quận 9  </a></li>
                    <li class="appear-animation fadeInUp appear-animation-visible" data-appear-animation="fadeInUp"
                        data-appear-animation-delay="900" style="animation-delay: 900ms;"><i class="fa fa-check "></i><a href="/thue-tro/sai-gon/quan-go-vap" > Thuê trọ Quận Gò Vấp  </a></li>
                    <li class="appear-animation fadeInUp appear-animation-visible" data-appear-animation="fadeInUp"
                        data-appear-animation-delay="900" style="animation-delay: 900ms;"><i class="fa fa-check "></i><a href="/thue-tro/sai-gon/quan-binh-thanh" > Thuê trọ Quận Bình Thạnh  </a></li>
                    <li class="appear-animation fadeInUp appear-animation-visible" data-appear-animation="fadeInUp"
                        data-appear-animation-delay="900" style="animation-delay: 900ms;"><i class="fa fa-check "></i><a href="/thue-tro/sai-gon/quan-tan-binh"> Thuê trọ Quận Tân Bình  </a></li>
                    <li class="appear-animation fadeInUp appear-animation-visible" data-appear-animation="fadeInUp"
                        data-appear-animation-delay="900" style="animation-delay: 900ms;"><i class="fa fa-check "></i><a href="/thue-tro/sai-gon/quan-tan-phu" > Thuê trọ Quận Tân Phú  </a></li>
                    <li class="appear-animation fadeInUp appear-animation-visible" data-appear-animation="fadeInUp"
                        data-appear-animation-delay="900" style="animation-delay: 900ms;"><i class="fa fa-check "></i><a href="/thue-tro/sai-gon/quan-phu-nhuan" > Thuê trọ Quận Phú Nhuận  </a></li>
                    <li class="appear-animation fadeInUp appear-animation-visible" data-appear-animation="fadeInUp"
                        data-appear-animation-delay="900" style="animation-delay: 900ms;"><i class="fa fa-check "></i><a href="/thue-tro/sai-gon/quan-2" > Thuê trọ Quận 2  </a></li>
                    <li class="appear-animation fadeInUp appear-animation-visible" data-appear-animation="fadeInUp"
                        data-appear-animation-delay="900" style="animation-delay: 900ms;"><i class="fa fa-check "></i><a href="/thue-tro/sai-gon/quan-3" > Thuê trọ Quận 3  </a></li>
                    <li class="appear-animation fadeInUp appear-animation-visible" data-appear-animation="fadeInUp"
                        data-appear-animation-delay="900" style="animation-delay: 900ms;"><i class="fa fa-check "></i><a href="/thue-tro/sai-gon/quan-10"> Thuê trọ Quận 10  </a></li>
                    <li class="appear-animation fadeInUp appear-animation-visible" data-appear-animation="fadeInUp"
                        data-appear-animation-delay="900" style="animation-delay: 900ms;"><i class="fa fa-check "></i><a href="/thue-tro/sai-gon/quan-11"> Thuê trọ Quận 11  </a></li>
                    <li class="appear-animation fadeInUp appear-animation-visible" data-appear-animation="fadeInUp"
                        data-appear-animation-delay="900" style="animation-delay: 900ms;"><i class="fa fa-check "></i><a href="/thue-tro/sai-gon/quan-4" > Thuê trọ Quận 4  </a></li>
                    <li class="appear-animation fadeInUp appear-animation-visible" data-appear-animation="fadeInUp"
                        data-appear-animation-delay="900" style="animation-delay: 900ms;"><i class="fa fa-check "></i><a href="/thue-tro/sai-gon/quan-5" > Thuê trọ Quận 5  </a></li>
                    <li class="appear-animation fadeInUp appear-animation-visible" data-appear-animation="fadeInUp"
                        data-appear-animation-delay="900" style="animation-delay: 900ms;"><i class="fa fa-check "></i><a href="/thue-tro/sai-gon/quan-6" > Thuê trọ Quận 6  </a></li>
                    <li class="appear-animation fadeInUp appear-animation-visible" data-appear-animation="fadeInUp"
                        data-appear-animation-delay="900" style="animation-delay: 900ms;"><i class="fa fa-check "></i><a href="/thue-tro/sai-gon/quan-8" > Thuê trọ Quận 8  </a></li>
                    <li class="appear-animation fadeInUp appear-animation-visible" data-appear-animation="fadeInUp"
                        data-appear-animation-delay="900" style="animation-delay: 900ms;"><i class="fa fa-check "></i><a href="/thue-tro/sai-gon/quan-binh-tan"> Thuê trọ Quận 8  </a></li>
                    <li class="appear-animation fadeInUp appear-animation-visible" data-appear-animation="fadeInUp"
                        data-appear-animation-delay="900" style="animation-delay: 900ms;"><i class="fa fa-check "></i><a href="/thue-tro/sai-gon/quan-7"> Thuê trọ Quận 7  </a></li>
                    <li class="appear-animation fadeInUp appear-animation-visible" data-appear-animation="fadeInUp"
                        data-appear-animation-delay="900" style="animation-delay: 900ms;"><i class="fa fa-check "></i><a href="/thue-tro/sai-gon/huyen-cu-chi"> Thuê trọ Huyện Củ Chi  </a></li>
                    <li class="appear-animation fadeInUp appear-animation-visible" data-appear-animation="fadeInUp"
                        data-appear-animation-delay="900" style="animation-delay: 900ms;"><i class="fa fa-check "></i><a href="/thue-tro/sai-gon/huyen-hoc-mon"> Thuê trọ Huyện Hóc Môn  </a></li>
                    <li class="appear-animation fadeInUp appear-animation-visible" data-appear-animation="fadeInUp"
                        data-appear-animation-delay="900" style="animation-delay: 900ms;"><i class="fa fa-check "></i><a href="/thue-tro/sai-gon/huyen-binh-chanh">Thuê trọ  Huyện Bình Chánh  </a></li>
                    <li class="appear-animation fadeInUp appear-animation-visible" data-appear-animation="fadeInUp"
                        data-appear-animation-delay="900" style="animation-delay: 900ms;"><i class="fa fa-check "></i><a href="/thue-tro/sai-gon/huyen-nha-be"> Thuê trọ Huyện Nhà Bè  </a></li>
                    <li class="appear-animation fadeInUp appear-animation-visible" data-appear-animation="fadeInUp"
                        data-appear-animation-delay="900" style="animation-delay: 900ms;"><i class="fa fa-check "></i><a href="/thue-tro/sai-gon/huyen-can-gio"> Thuê trọ Huyện Cần Giờ  </a></li>
                </ul>
            </div>
        </div>
    </div>


</div>